### ISSUE TITLE
Mit YForm 3 testen und Conflicts anpassen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/cache_warmup#103]
Cache-Warmup erwartet zur Zeit noch YForm 2, das ist in der `package.yml` unter `conflicts` definiert: https://github.com/FriendsOfREDAXO/cache_warmup/blob/a24b590a475d0c4966c739d023577cf7825563e7/package.yml#L40

TODO:
1. Prüfen, ob Cache-Warmup für die Verwendung mit YForm 3 angepasst werden muss, ob sich also an den Feldtypen etwas geändert hat: https://github.com/FriendsOfREDAXO/cache_warmup/blob/a24b590a475d0c4966c739d023577cf7825563e7/lib/selector.php#L72  
Falls ja: Cache-Warmup so anpassen, dass es sowohl mit YForm 2 als auch mit dem neuen YForm 3 funktioniert.
2. Conflicts anpassen

**Comment by AWqxKAWERbXo** [comment]
Wieso erfordert cache warmup überhaupt yform?

**Comment by schuer** [comment]
Es erfordert es nicht (siehe [requires](https://github.com/FriendsOfREDAXO/cache_warmup/blob/a24b590a475d0c4966c739d023577cf7825563e7/package.yml#L29-L31)), aber es selektiert dessen Medien, sofern installiert, und es vermutet einen Conflict bei einem Major-Update (so wie jetzt von 2 auf 3). Es könnte ja sein, dass sich dabei die Feldbezeichnungen ändern und dann womöglich im Warmup Fehler fliegen.

**Comment by AWqxKAWERbXo** [comment]
Ich will nicht die Hand dafür ins Feuer legen, aber dahingehend hat sich bei den Medien nichts verändert.
