### ISSUE TITLE
Fehler in der Konsole - TypeError: data.substr

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/cache_warmup#104]
Sobald das Popup aufgeht, erscheint folgender Fehler:

> TypeError: data.substr is not a function. (In 'data.substr(0, 30)', 'data.substr' is undefined)

**Comment by schuer** [comment]
@tbaddade Ich kann das Problem leider nicht nachvollziehen. Kannst du weitere Angaben machen, wie es dazu kommt? Welcher Browser, welches REDAXO? Gibt es in der Konsole weitere Hinweise auf Fehler? Irgendwelche Besonderheiten an der REDAXO-Installation, die sowas auslösen könnten?

**Comment by schuer** [comment]
Ping @tbaddade

**Comment by tbaddade** [comment]
Ich kann nicht mehr sagen wann das genau passierte und mir fehlt auch gerade der Bezug zu dem  Projekt. Sorry für mein fehlendes Feedback @schuer 

Ich schließe
