### ISSUE TITLE
Problem mit aktuellem YRewrite: 404

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/cache_warmup#106]
Siehe
https://github.com/yakamara/redaxo_yrewrite/issues/301
404 in cache_warmup bei yrewrite 

Ggf. bei @tyrant88 nachfragen, da wurde es meines Wissens für search_it gelöst.

**Comment by schuer** [comment]
Danke für den Hinweis. Sollte hiermit gefixt sein.
(Nebenbei: YRewrite hätte aufgrund dieser Breaking Changes nicht 2.6 sondern 3.0 sein müssen.)

**Comment by tyrant88** [comment]
ich hab keinen Schimmer worum es hier geht :-)

**Comment by schuer** [comment]
Ich auch nicht ;)
