### ISSUE TITLE
Internal Server Error (500)

### ISSUE THREAD

**Issue by chandany** [FriendsOfREDAXO/cache_warmup#108]
Error thrown with message "Call to a member function getArticles() on null"

Stacktrace:
#23 Error in rex:///module/52/output:3
#22 require in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/cache/addons/structure/120.1.content:111
#21 require in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/addons/structure/plugins/content/lib/article_content.php:99
#20 rex_article_content:getArticle in rex:///template/3:51
#19 require in rex:///template/2:6
#18 require in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/addons/structure/plugins/content/lib/article_content_base.php:405
#17 rex_article_content_base:{closure} in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/lib/util/timer.php:57
#16 rex_timer:measure in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/addons/structure/plugins/content/lib/article_content_base.php:406
#15 rex_article_content_base:getArticleTemplate in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/addons/cache_warmup/lib/generator_pages.php:23
#14 cache_warmup_generator_pages:generateCache in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/addons/cache_warmup/pages/generator.php:39
#13 include in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/lib/packages/package.php:280
#12 rex_package:includeFile in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/lib/be/controller.php:482
#11 rex_be_controller:{closure} in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/lib/util/timer.php:57
#10 rex_timer:measure in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/lib/be/controller.php:483
#9 rex_be_controller:includePath in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/lib/be/controller.php:432
#8 rex_be_controller:includeCurrentPageSubPath in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/addons/cache_warmup/pages/index.php:4
#7 include in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/lib/packages/package.php:280
#6 rex_package:includeFile in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/lib/be/controller.php:482
#5 rex_be_controller:{closure} in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/lib/util/timer.php:57
#4 rex_timer:measure in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/lib/be/controller.php:483
#3 rex_be_controller:includePath in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/lib/be/controller.php:415
#2 rex_be_controller:includeCurrentPage in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/backend.php:233
#1 require in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/src/core/boot.php:141
#0 require in /is/htdocs/wp10474332_WNF97EX2G2/www/redaxo/redaxo/index.php:9

-------------------------------→
#23 Error in rex:///module/52/output:3

<?php
//$articles = rex_category::getCurrent()->getArticles();
/*
Ohne das (true) gibts noch größeres badbum. ;)
*/
$articles = rex_category::getCurrent()->getArticles(true);

if (count($articles)) {
  $output[] = '<div class="teaser clearfix"><div class="row">';
    foreach ($articles as $article) {
      if ($article->getValue('status') != 0&& $article->getValue('art_teaser') == '') { // Offline
        if ($article instanceof rex_article && !$article->isStartArticle()) {
            $output[] = '<div class="col-lg-5"><img class="image-deco" src="index.php?rex_media_type=thumb&rex_media_file='.$article->getValue('art_pic').'" alt="'.$article->getValue('art_title').'"></div>
<div class="col-lg-7"><h2><a class="hover-title" href="'.rex_geturl($article->getValue('id'), rex_clang::getCurrentId()).'">'.$article->getValue('name').'</a></h2> <p>'.$article->getValue('art_description').'</p>
<a class="btn btn-theme" href="'.rex_geturl($article->getValue('id'), rex_clang::getCurrentId()).'" class="btn btn-theme"><span>{{ more_info }}</span></a><div class="hline"></div></div>';
        }
      }
    }
  $output[] = '</div><hr></div>';
} 

if(!rex::isBackend()) {
  echo implode('',$output);
} else {
  echo '
  <div id="artikelliste" class="bereichswrapper">
    <div class="form-horizontal output">
     <h2>Artikelliste</h2>
       <div class="form-group">
         <div class="col-sm-12 control-label">
           <p>Die Artikelliste wird im Frontend ausgegeben.</p>
         </div>
       </div>
    </div>
  </div>

<style>
#artikelliste .bereichswrapper {
  margin: 5px 0 5px 0;
  background: #f5f5f5;
  padding: 5px 15px 5px 15px;
  border: 1px solid #9da6b2;
}

#artikelliste .control-label {
  text-align: left;
  font-weight: normal;
  font-size: 12px;
  margin-top: -6px;
}

#artikelliste  h2 {
  font-size: 12px !important;
  padding: 0 10px 10px 10px;
  margin-bottom: 15px;
  width: 100%;
  font-weight: bold;
  border-bottom: 1px solid #31404F;
}

</style>
';
}
?>
///

**Comment by schuer** [comment]
Hi @chandany, du hast vermutlich einen Fehler in deinem Modul mit der ID 52 oder deinem Template mit der ID 3. Cache-Warmup deckt diese nur auf, aber sie sollten vermutlich auch entstehen, wenn du die Website an der passenden Stelle aufrufst.

**Comment by chandany** [comment]
Vielen Dank. Hatte das hier aus den Augen verloren. ;)
