### ISSUE TITLE
stoppt bei cache anlegen mit Fehler

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/cache_warmup#115]
Hallo
Ich erhalte diese Fehler beim Cache anlegen:

TypeError thrown with message "imagecreatetruecolor(): Argument #1 ($width) must be of type int, string given"

Stacktrace:
#19 TypeError in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/addons/media_manager/lib/effects/effect_resize.php:57
#18 imagecreatetruecolor in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/addons/media_manager/lib/effects/effect_resize.php:57
#17 rex_effect_resize:execute in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/addons/media_manager/lib/media_manager.php:116
#16 rex_media_manager:applyEffects in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/addons/media_manager/lib/media_manager.php:65
#15 rex_media_manager:create in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/addons/cache_warmup/lib/generator_images.php:19
#14 cache_warmup_generator_images:generateCache in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/addons/cache_warmup/pages/generator.php:44
#13 require in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/lib/packages/package.php:280
#12 rex_package:includeFile in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/lib/be/controller.php:481
#11 rex_be_controller:{closure} in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/lib/util/timer.php:57
#10 rex_timer:measure in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/lib/be/controller.php:463
#9 rex_be_controller:includePath in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/lib/be/controller.php:431
#8 rex_be_controller:includeCurrentPageSubPath in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/addons/cache_warmup/pages/index.php:6
#7 require in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/lib/packages/package.php:280
#6 rex_package:includeFile in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/lib/be/controller.php:481
#5 rex_be_controller:{closure} in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/lib/util/timer.php:57
#4 rex_timer:measure in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/lib/be/controller.php:463
#3 rex_be_controller:includePath in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/lib/be/controller.php:414
#2 rex_be_controller:includeCurrentPage in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/backend.php:239
#1 require in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/src/core/boot.php:143
#0 require in /var/www/vhosts/meinedomain.ch/httpdocs/redaxo/index.php:9

**Comment by AWqxKAWERbXo** [comment]
Hi @abra100pro - das ist kein Fehler von cache_warmup, sondern wie man sieht, aus dem Effekt "Resize". Schau mal, ob du im REDAXO Media Manager ein Profil hast mit einem Resize-Effekt drin, in dem statt `100` (richtig) z.B. `100px` (falsch) steht.

**Comment by abra100pro** [comment]
Hi Alexander, ich hoffe, ich mach den issue mit meiner Antwort nicht wieder auf – wollte dir aber sagen, dass Du richtig lagst – das wusste ich nicht. danke dir vielmals und alles Gute im '23 (und auch danach ;-)!

**Comment by ansichtsache** [comment]
hi, ich bekomme den fehler auch – kann aber keinen resize-typ mit dem gennanten fehler finden …

**Comment by AWqxKAWERbXo** [comment]
@ansichtsache speichere die jeweiligen Effekte (nicht Profile) mal frisch ab.

**Comment by ansichtsache** [comment]
@alxndr-w  leider keine besserung
