### ISSUE TITLE
Umleitungen aus YRewrite werden nicht ignoriert

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/cache_warmup#116]
**Description / Beschreibung**
![image](https://user-images.githubusercontent.com/3855487/214809215-f2bee3df-d6a8-4526-8386-82506535acfe.png)

Ein Artikel, der eigentlich nur eine Umleitung ist, führt in cache_warmup zu einem Whooops, weil trotzdem versucht wird, den Cache zu generieren, aber in Wahrheit gar keinen Cache benötigt.

cache_warmup sollte diese Form von Umleitungen ignorieren.

**Affected versions / Verwendete Versionen**

REDAXO: 
PHP:
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

**Comment by schuer** [comment]
Ich kann das Problem nicht nachvollziehen. Getestet mit Umleitung zu einem Artikel und Umleitung zu URL mit `tel:12345`.

Wenn Cache Warmup an der Stelle im betroffenen Projekt einen Whoops produziert, wird ein normaler Seitenaufruf an gleicher Stelle vermutlich ebenso einen Whoops produzieren.
