### ISSUE TITLE
Usability: Registerkarte verschieben

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/cache_warmup#117]
**Feature description / Feature Beschreibung**
Ich habe mir heute fast den Wolf gesucht, wo ich Redaxo einheizen kann... Ich würde es im Sinne der Usability besser finden, wenn die Registerkarte direkt an die bestehenden angehängt wird und sich nicht rechts ausrichtet. (siehe Screenshot)
<img width="2261" alt="Bildschirmfoto 2023-02-09 um 12 16 45" src="https://user-images.githubusercontent.com/10958385/217800331-a06c71bc-f559-4b35-9345-6057c970c2b7.png">

EDIT: Falls ich hier auf Zustimmung stoße, würde ich auch einen PR zur Verfügung stellen...

**Comment by schuer** [comment]
Bin voll bei dir. Allerdings hast du das »falsche« Cache-Warmup im Einsatz, nicht dieses hier von FOR.
Magst du das Issue dort melden, dann schließe ich hier direkt.

**Comment by schuer** [comment]
<img width="940" alt="Screenshot 2023-02-09 at 12 34 33" src="https://user-images.githubusercontent.com/1297466/217801909-bd0d0692-e417-49c6-8d6d-6e215a367667.png">

**Comment by dpf-dd** [comment]
Ahh ok, ich hatte heute Morgen die 1.0.0 aus dem Installer genommen und noch nicht die neue Dev-Version. Dann ist ja bereits alles erledigt und ich danke dir für die schnelle Rückmeldung :)
