### ISSUE TITLE
Diskussion: Name des Addons

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/cache_warmup#2]
Der Name ist nur ein Schnellschuss und darf gern als provisorisch angesehen werden.
Weiß jemand einen besseren?

**Comment by eaCe** [comment]
Würde zumindest noch das Wort "cache" hinzufügen, damit man direkt versteht um was es geht.

**Comment by staabm** [comment]
im symfony umfeld heißen diese dinger CacheWarmer

**Comment by gharlan** [comment]
Wobei das die einzelnen Dinger sind, die Gesamtaktion nennt sich dann auch warmup (es gibt den Befehl `bin/console cache:warmup`).
Ich wäre wohl für cache-warmup oder so ähnlich.

**Comment by schuer** [comment]
Okay, also neuer Vorschlag: **Cache Warm-up**.
(Rechtschreibung: Warm-up schreibt man mit Bindestrich. Auch wenn es ohne irgendwie schöner aussähe.)

**Comment by gharlan** [comment]
Bist du sicher? Ich glaube, es geht beides: http://www.dictionary.com/browse/warmup?s=t

**Comment by schuer** [comment]
Hm, ohne Bindestrich scheint eine Art Fallback zu sein. Alle Quellen, die ich bisher gesehen habe, hatten mit Bindestrich.
Aber umso besser, dann machen wir **Cache-Warmup**? Oder Cache Warmup?

**Comment by gharlan** [comment]
Wie schon auf skype geschrieben, werden Addonnamen (also der Addonkey) in der Regel klein geschrieben, daher würde ich das wohl beibehalten (auch weil der Ordner ja genauso heißen muss).
Bisher ist eher ein Unterstrich statt Bindestrich üblich, fände den Bindestrich aber eigentlich schöner. Ist mir aber eigentlich auch egal.

**Comment by schuer** [comment]
Das Repo heißt also `cache-warmup`, und der Addon-Titel ist »Cache-Warmup«.

Ich schließe das jetzt einfach mal direkt, damit wir nicht lange rumreden. Wer unbedingt einen anderen Namen will, öffne das Ticket wieder ;)
