### ISSUE TITLE
Leeres Popup wenn keine Artikel / Bilder vorhanden sind

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/cache_warmup#23]
Oh, der erste Issue :)

**Comment by AWqxKAWERbXo** [comment]
@aeberhard Glückwunsch zu deinem ersten Issue. Du wirst sehen, das macht sehr viel Spaß hier auf Github :)

**Comment by schuer** [comment]
Na endlich ist mal ein bisschen was los hier. Danke, @aeberhard :)

Ich habe gerade mal kurz drüber geschaut und bemerkt, dass ich beim Config-JSON, das die zu generierenden Bilder und Seiten enthält, etwas zu nachlässig war. Seine Struktur ist inkonsistent, wenn mal keine Bilder oder Seiten vorhanden sind, so wie in deinem Fall.

Das würde ich gerne in Ruhe überarbeiten, nur leider ist ab morgen Urlaub angesagt.
Nicht wundern also, wenn das Issue noch ein bisschen rumliegt.

**Comment by aeberhard** [comment]
@schuer Dann mal einen schönen Urlaub Dirk!!

@alexplusde ich meinte den ersten Issue hier beim cache_warmup :)

**Comment by schuer** [comment]
Nicht wundern, mir brannte es jetzt doch unter den Nägeln, die Bugfixes noch vorm Urlaub einzuschieben…
