### ISSUE TITLE
Warnings im Systemlog

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/cache_warmup#24]
Jede Menge Warnings im Systemlog
`Cannot modify header information - headers already sent by`

Vielleicht kann man das durch 

```
        while (ob_get_length()) {
            ob_end_clean();
        }
```

unterdrücken ...

**Comment by staabm** [comment]
Steht im log an welcher stelle der output schon gestartet wurde?

**Comment by aeberhard** [comment]
![image](https://cloud.githubusercontent.com/assets/330560/17766792/2056bf5e-652d-11e6-828b-cb10349f8958.png)

**Comment by schuer** [comment]
Das Addon benutzt die `rex_media_manager`-Klasse aus dem media_manager. Dort fliegen die Warnings.

Besteht hier Handlungsbedarf für Cache-Warmup? Für mein Empfinden nicht, aber ich bin gespannt auf Meinungen von @gharlan und @staabm.

**Comment by staabm** [comment]
Wo rufst du sendMedia() auf?

https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/media_manager/lib/managed_media.php#L134

**Comment by schuer** [comment]
Es wird nur `media_manager` verwendet, nicht `managed_media`, siehe https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/lib/media_manager.php

**Comment by staabm** [comment]
Ahh hier ist es https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/lib/media_manager.php#L24

**Comment by staabm** [comment]
Durch sendMedia() startest du die ausgabe

**Comment by schuer** [comment]
Ja, aber das, was dann passiert, ist ja Teil des media_managers, nicht mehr Teil von Cache-Warmup, oder sehe ich das falsch? Für mein Empfinden müsste dann im Cache-Warmup keine Warnings unterbunden werden.

**Comment by staabm** [comment]
Wenn man sendImage() aufruft ist zu erwarten dass output passiert. D.h. Danach kannst du mit deinem addon keine anderen header mehr senden

**Comment by schuer** [comment]
Ich habe nochmal nachgedacht, und das Problem ist folgendes:
- der Output kommt vom media_manager (siehe [managed_media.php#L159-L162](https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/media_manager/lib/managed_media.php#L159-L162)). Dort ist er auch sinnvoll, denn wie @staabm schon sagt: man will dort ja Output.
- im Cache-Warmup ist der Output nicht sinnvoll, denn das möchte nur Cachefiles generieren, nicht aber das generierte Bild auch ausgeben.
- Gleichzeitig darf Cache-Warmup den Output nicht unterbinden, denn er wird für die Fehlerverarbeitung verwendet. Der media_manager sendet grundsätzlich einen HTTP 200, auch wenn die Bildverarbeitung schief gelaufen ist, weil z. B. zu wenig RAM verfügbar war. Deshalb ist Cache-Warmup gezwungen, den Content zu analysieren. Um das abzukürzen: Wenn im Content ein `<div class="rex-page-header">…` zurück kommt, ist das Teil einer Fehlermeldung, und es ist also etwas schief gelaufen (siehe [cache-warmup.js#L399-L401](https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/assets/js/cache-warmup.js#L399-L401)).

Mir scheint, Cache-Warmup müsste zusätzlich noch die Klasse `rex_managed_media` extenden, um dort den Output gezielt zu unterbinden. Will man das? Denn schließlich erhöht sich damit auch der Pflegeaufwand des Addons, das damit immer mehr Updates des media_managers nachziehen müsste.

Ich bin allerdings nicht PHP-fit genug, um das richtig einschätzen zu können.
Wie ist eure Meinung?

_(Lasst euch Zeit, ich werden in den kommenden 1–2 Wochen kaum hier mitlesen.)_

**Comment by schuer** [comment]
> (Lasst euch Zeit, ich werden in den kommenden 1–2 Wochen kaum hier mitlesen.)

Bin übrigens wieder da und gespannt auf eure Meinungen :)

**Comment by schuer** [comment]
Habe mir das Thema nochmal vorgenommen: Anders als oben beschrieben darf das Addon den Output doch gerne vollständig unterbinden, denn es gibt eigentlich nur einen relevanten Fehler — wenn zuwenig RAM verfügbar ist, um das Cachefile eines Bilds zu generieren —, und der fliegt in jedem Fall.

Das bedeutet: Macht die Page eine Ausgabe (beginnt immer mit `<header class="rex-page-header`, weil aktuell fest im Core verdrahtet), ist etwas schief gelaufen. In allen anderen Fällen — z. B. auch wenn ein Bild referenziert wird, aber gar nicht im Filesystem vorhanden ist —, bleibt die Ausgabe leer.

Für die Fehlerbehandlung reicht uns das hier aus, deshab können wir schlicht den Output unterbinden, und alles ist fein :)
