### ISSUE TITLE
Fehler wenn ein Bild z.B. in den Sprachen abgelegt wird

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/cache_warmup#25]
Wenn man ein clang_-Bild anlegt bekommt man einen Fehler:

Error while executing statement "SELECT clang_test FROM rex_article"! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'clang_test' in 'field list'

**Comment by AWqxKAWERbXo** [comment]
Wie meinst du das? Ist das ein Meta-Feld, was du für Artikel angelegt hast? Dann heißt das Feld doch eig. ohnehin `art_clang_test`. Oder hast du einer Sprache ein Meta-Feld zugewiesen? Dann müsste der Befehl ja `...FROM rex_clang` lauten.

**Comment by eaCe** [comment]
Der Sprache ist das Meta-Feld zugewiesen. Warum der Fehler auf article referenziert, weiß ich auch nicht :)

**Comment by AWqxKAWERbXo** [comment]
Wenn ich das überfliege, liegt es daran, dass angenommen wird, Bilder in meta-Infos wären immer nur einem Artikel (oder eine Kategorie, die ja ein Artikel ist) zugewiesen.

https://github.com/FriendsOfREDAXO/cache_warmup/blob/6c28d26bf800044bfde82bc74eea3cf331a49c54/lib/selector.php#L106

**Comment by schuer** [comment]
Ich sag nur: https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/lib/selector.php#L26

Danke für den Hinweis!
