### ISSUE TITLE
Falsche Anzahl der Artikel

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/cache_warmup#43]
Hier werden alle Artikel aller Sprachen geholt.
https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/lib/selector.php#L230

Anschließend wird für jedes Result zusätzlich jede Sprache hinzugefügt.
https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/lib/selector.php#L246

Das ergibt bei 2 Sprachen die doppelte Anzahl von `$items`.

**Comment by staabm** [comment]
hmm sieht so aus als könnte man sich die loop über die sprachen komplett sparen, oder?

**Comment by tbaddade** [comment]
> sieht so aus als könnte man sich die loop über die sprachen komplett sparen

Denke ich auch. Im Query müsste aber zusätzlich ein Join auf die Sprachen, da aktuell nur Sprachen die online sind berücksichtigt werden.

Diese Methode könnte dann gelöscht werden
https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/lib/selector.php#L269

**Comment by schuer** [comment]
Danke!

**Comment by schuer** [comment]
> Jetzt holst du alle Online-Artikel in allen Sprachen. Zuvor hattest du es nur auf Sprachen angewendet, die ebenfalls online waren.

https://github.com/FriendsOfREDAXO/cache_warmup/commit/13de2680ae5af9efff147d53ebb479da743dd3b1#commitcomment-20552422

**Comment by staabm** [comment]
naja wenn wir jetzt nicht mal ne redaxo installation mit 100.00 artikel und zig mediatypes "aufwärmen" können ;-)

**Comment by schuer** [comment]
…die bei Rüdiger hostet und der schimpft dann, wenn der Server unter der Last zusammenbricht ;)
