### ISSUE TITLE
Exception in R <5.1 wegen fehlendem Feature 'Status (online/offline) für Sprachen'

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/cache_warmup#48]
Erst mit REDAXO 5.1 ist **Status (online/offline) für Sprachen** (siehe [Release-Info](https://github.com/redaxo/redaxo/releases/tag/5.1.0)) hinzugekommen, Cache-Warmup prüft jedoch das Feature vorher nicht, so dass in Versionen <5.1 eine Exception fliegt:

```Error while executing statement using params [1,1]! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.status' in 'where clause'```

Entweder Prüfung einbauen oder REDAXO-Mindestversion auf 5.1 erhöhen. Ich persönlich würde gerne prüfen, denn abgesehen von diesem Feature sollte Cache-Warmup eigentlich problemlos auch mit 5.0 funktionieren. Zumindest hat es das zu Beginn der Entwicklung ;)

**Comment by staabm** [comment]
👍 für feature test

**Comment by tbaddade** [comment]
Wäre dafür die REDAXO Min-Version hochzusetzen. Allein, damit die Leute auch den Core aktualisieren.

**Comment by staabm** [comment]
Es wird einige geben die den core nicht einfach updaten können, aber sich dennoch/erst recht über eine funktionierende r5.0/5.1 version freuen würden.

Solange es keinen grund gibt technisch die min version zu erhöhen würde ich definitiv nen feature-test einbauen.

**Comment by schuer** [comment]
Ich verstehe @tbaddade s Intention, bin aber bei Markus’ Meinung, dass das Addon nicht dafür herhalten sollte, Nutzer:innen zum Update zu drängen. Habe deshalb einen PR gemacht.
