### ISSUE TITLE
Compat: Anpassungen für R 5.3 übernehmen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/cache_warmup#50]
Media Manager: Fehlende Methode zur Referenzierung von generiertem Bild
https://github.com/redaxo/redaxo/issues/707

Commit: https://github.com/redaxo/redaxo/commit/e156f08a0631873c7a63174dafe16b1d89908284

**Comment by staabm** [comment]
FYI: in meinen Augen muss die Anpassung im rex-core überarbeitet werden, damit addons sich genau deswegen nicht anpassen müssen... innerhalb eines normalen minor-releases sollten solche BC breaks nicht enthalten sein.

**Comment by gharlan** [comment]
Es fehlt hier im Addon übrigens die Abhängigkeit zum media_manager, etwas wie `^2.0`.
Denn sollten wir BC brechen, würden wir die Version des Addons auf 3.0 anheben.
Und wenn hier im Addon dann eine Versionsbedingung wie oben drin wäre, dann würde das Core-Update abgelehnt werden, wenn man cache_warmup in einer nicht kompatiblen Version hat.

**Comment by schuer** [comment]
@gharlan Ich hatte die Abhängigkeit zum media_manager mal drin (siehe [Commit](https://github.com/FriendsOfREDAXO/cache_warmup/commit/219400a246b5a494d4ecda3b9895a4097cb6792e#diff-0d40a7e304bb04123a05f78b520b0e0e)), habe sie aber deshalb entfernt, weil ich davon ausgegangen bin, dass der media_manager nicht zwangsläufig für jede REDAXO-Installation benötigt wird, also nicht mandatory ist. Wenn jemand z. B. ausschließlich Textinhalte mit REDAXO verwaltet (geht in Richtung Headless CMS), also nur Structure installiert hat, dann würde Cache-Warmup eben auch nur Seiten generieren, keine Bilder. Gleiches natürlich andersrum: Wenn jemand Structure deaktiviert hat und nur Bilder verwaltet, dann generiert Cache-Warmup halt keine Seiten.

Die Prüfung findet innerhalb des Addons statt, deshalb hatte ich die `package.yml` wieder reduziert.
— Man bräuchte eine Deklaration wie: »Wenn media_manager, dann bitte nur in Version 2.«

**Comment by gharlan** [comment]
Ah verstehe, soweit habe ich nicht gedacht.

Du könntest Konflikte notieren:
```yaml
conflicts:
    packages:
        media_manager: ">= 3"
        structure: ">= 3"
```

So hättest du weiterhin keine festen Abhängigkeiten, hättest aber trotzdem sichergestellt, dass das Addon nicht mit eventuell inkompatiblen Addons zusammen installiert wird.

**Comment by schuer** [comment]
Ha, das kannte ich noch nicht. Perfekt, das könnten wir doch so übernehmen. Danke!

**Comment by staabm** [comment]
Wenn ich jan richtig verstanden habe sollte nach https://github.com/redaxo/redaxo/commit/a4c73045f84858e1b83b6b1451324989e3213a06 jetzt kein BC problem mehr bestehen. Bitte mal das aktuelle addon - ohne anpassungen - mit 5.3 versuchen

**Comment by schuer** [comment]
Anpassungen des Media Managers wurden zurückgenommen, so dass hier kein weiterer Handlungsbedarf ist, siehe https://github.com/redaxo/redaxo/issues/707#issuecomment-279368129
