### ISSUE TITLE
Dynamische Seiten

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/cache_warmup#52]
@schuer meinst du, man könnte ggf. Support für dynamische Seiten implementieren? (z.B. über https://github.com/tbaddade/redaxo_url) generierte URLs? 

Entweder das AddOn macht es out-of-the-box, oder es stellt einen EP bereit, damit man eigene URLs hinzufügen kann.

**Comment by schuer** [comment]
Sollte kein Problem sein, denke ich. Kenne das Addon nicht, aber das sollte doch bestimmt kein Problem sein, die Inhalte zu generieren (Ping @tbaddade).

**Comment by tbaddade** [comment]
> Kenne das Addon nicht

Tss 🤔 

>aber das sollte doch bestimmt kein Problem sein, die Inhalte zu generieren

Der Dev muss die Inhalte selber cachen. Das macht nicht das Url-AddOn.

Am sinnvollsten erscheint es mir hier[1] einen EP zu registrieren, der Urls entgegennimmt und dann entsprechen verarbeitet.

[1] https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/pages/generator.php#L27

**Comment by schuer** [comment]
»Kenne das Addon nicht« bezieht sich natürlich auf den Code. Kenne den Code nicht. Habe noch nicht unter die Haube geschaut :)

**Comment by schuer** [comment]
Sorry, noch eine Anmerkung: Bevor wir das AddOn anpassen, sollten wir uns bewusst machen, dass REDAXO den Cache für Inhalte ja sehr schnell generieren kann. Das ist ja quasi nur eine Sekunden-Aufgabe, selbst für große Mengen von Inhalten. Aufwendig sind ja lediglich die Bilder, und die sollten eigentlich aus allen gängigen Quellen bereits erfasst werden: Seiten, Metadaten, YForm.

Ich würde ungern Features implementieren, die nicht notwendig sind.

**Comment by hirbod** [comment]
Nur eine kurze Zwischenfrage (mir geht es hier auch eher um die Bilder):
woher weiß das AddOn, welcher Bildtyp für eine Fotospalte innerhalb von yForm genutzt wird?

Wird einfach pauschal jeder Media Manager Typ für dieses Bild angewendet? Wäre dann zwar etwas Overkill, aber würde meine Feature-Anfrage handeln. Ansonsten wüsste ich nicht, wie das AddOn hier überhaupt mit den Bildern funktioniert. Ich dachte eigentlich, vom Verständnis, es wird einfach per AJAX die Seite aufgerufen. (wodurch ja der Cache erstellt wird)

**Comment by schuer** [comment]
@Hirbod https://github.com/FriendsOfREDAXO/cache_warmup#ich-bin-entwicklerin-was-genau-macht-das-addon

Es werden alle _verwendeten_ Bilder in allen _vorhandenen_ Mediatypen generiert.

**Comment by hirbod** [comment]
Verstehe. Dann close :).

**Comment by schuer** [comment]
Ist mir sehr recht. Falls noch jemand von den Mitlesern drauf anspringen möchte, öffnet gerne bei Bedarf wieder.
