### ISSUE TITLE
REDAXO 5.3 Fehler

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/cache_warmup#53]
ErrorException thrown with message "Cannot make static method rex_media_manager::sendMedia() non static in class cache_warmup_media_manager"

Stacktrace:
#0 ErrorException in /var/www/clients/client1/web205/web/public/redaxo/src/addons/cache_warmup/lib/media_manager.php:0

<img width="1028" alt="bildschirmfoto 2017-02-11 um 17 40 49" src="https://cloud.githubusercontent.com/assets/504909/22855464/481e77c2-f081-11e6-93c3-96cb9ea34fee.png">

**Comment by isospin** [comment]
du warst schneller, bei mir ist auch gerade der gleiche fehler geflogen...

**Comment by staabm** [comment]
Vermutlich weitere nebenwirkung von https://github.com/redaxo/redaxo/commit/e156f08a0631873c7a63174dafe16b1d89908284

Muss im rex core gefixed werden
