### ISSUE TITLE
R 5.3 Media Manager: Header prüfen und übernehmen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/cache_warmup#54]
Die großen Anpassungen von neulich (#50) wurden zurückgenommen, allerdings sind ein paar kleine Anpassungen drin geblieben, die hier mal geprüft und ggfls übernommen werden sollten:

* [MediaManager: Bilder werden immer mit Status 200 geliefert](https://github.com/redaxo/redaxo/pull/1031/)
* [Media Manager: Revert](https://github.com/redaxo/redaxo/pull/1037)

Komplette History: https://github.com/redaxo/redaxo/commits/master/redaxo/src/addons/media_manager/lib/media_manager.php

Speziell zum Status 200 beachten: Entspricht das immer noch dem zu erwartenden Verhalten in unserem JS? https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/assets/js/cache-warmup.js#L398-L403

```js
.done(function (data) {
    // special: error on success (http status 200)
    // media manager returns 200 even if an image cannot be generated (too big, RAM exceeded)
    // we assume an error if response starts with rex-page-header
    // otherwise page will return blank if stuff works out as expected
    if (data.substr(0, 30) === '<header class="rex-page-header') {
```

**Comment by staabm** [comment]
falls du jetzt wg. 5.3 irgendwas ändern musst, bitte immer mit PR, damit wir sehen ob es nicht ein R5.3 problem ist

**Comment by gharlan** [comment]
Wegen Status 200 verstehe ich nicht ganz.
Für mich stellt sich das so da: Durch die größere Änderung kam ein Bug rein, sodass die Anfragen nie mehr mit Status 304 beantwortet wurden. Das hatte Axel dann gefixt, somit funktionierte 304 wieder so wie vorher. Dann haben wir die große Änderung rückgängig gemacht, der Fix wäre somit theoretisch überflüssig, da der Bug durch das Zurücksetzen auch wieder verschwunden wäre.

**Comment by schuer** [comment]
@gharlan Ich habe leider gerade nicht so recht die Zeit, das zu prüfen. Bisher war es offenbar so, dass der Media Manager immer 200 geliefert hat, auch wenn ein Fehler aufgetreten ist. Zumindest hatte ich es so als JS-Comment notiert.

Ich habe eben nur die PRs gesehen und bin davon ausgegangen, dass Teile davon im Release gelandet sind. Sollte das nicht der Fall sein, ist dieses Issue obsolet. Es war nur als Notiz gedacht, mal rundum zu prüfen, ob irgendwelche Anpassungen für Cache-Warmup übernommen werden müssen.

**Comment by schuer** [comment]
Ich habe es mir jetzt endlich mal näher angeschaut, und es gibt keine merklichen Anpassungen, die wir für Cache-Warmup übernehmen müssten. Auch nicht mit dem kommenden Media Manager 2.3.0-Release, zumindest nicht im aktuellen Stand. Der Header-Kram ist obsolet, weil wir das generierte Bild sowieso nicht ausgeben, und die anderen Anpassungen sind ja zurückgenommen worden und nicht in R 5.3 eingeflossen.

Nur eine Sache ist neu, die ich nicht abschätzen kann: Die `session_abort()`-Nummer, die @staabm eingebracht hat. Ist das auch notwendig oder sinnvoll für Cache-Warmup?

```php
// prevent session locking trough other addons
if (function_exists('session_abort')) {
    session_abort();
} else {
    session_write_close();
}
```

https://github.com/redaxo/redaxo/blob/6ac9a37502c9cef2508cca7f3e7cab33b3645b8c/redaxo/src/addons/media_manager/lib/media_manager.php#L213-L218

@gharlan oder @staabm, könnt ihr was dazu sagen?

**Comment by staabm** [comment]
aufgrund der session abort geschichte könntest du bilder parallel via warmup generieren oder du lässt es wie es ist und der user kann jetzt während dem generieren im gleichen browser besser nebenbei das backend bedienen

**Comment by schuer** [comment]
Letzteres klingt sinnvoller, oder? Also dass das Backend nachwievor nutzbar ist. Deshalb wird ja überhaupt erst das Popup benutzt.

Wie würdet ihr entscheiden?

**Comment by staabm** [comment]
Ich denke es funktioniert bisher ganz gut, daher lass es ruhig wie es ist

**Comment by schuer** [comment]
Okay, dann also close. Falls doch noch was auffällt: Reopen, wie üblich :)
Danke!
