### ISSUE TITLE
Addon + customizer plugin

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/cache_warmup#56]
<img width="662" alt="bildschirmfoto 2017-02-26 um 01 10 12" src="https://cloud.githubusercontent.com/assets/504909/23335928/61ea37c8-fbc0-11e6-88ec-b1cd838932c0.png">

Eigentlich steht an der Stelle im Header der Link zum Frontend. Ich weiss nicht, ob hier cache_warmup aufräumen muss, oder aber das customizer-plugin.

Ggf. weiß hier @tbaddade bescheid!

**Comment by schuer** [comment]
Danke @Hirbod, schaue ich mir an.
