### ISSUE TITLE
ChunkSize Parameter defaults

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/cache_warmup#58]
Die defaults für die chunk parameter exisitieren schon sehr lange. Seitdem wurden einige optimierungen im code durchgeführt, sodass wir die aktuellen werte hinterfragen sollten.

https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/boot.php

Annahme: man kann deutlich höhere Werte benutzen sodass auch für seiten mit sehr vielen Bildern und MediaTypes das ganze schnell/schneller läuft. Ich habe nicht gestested was sinnvoll ist, aber ggf. Kann jmd Erfahrungswerte liefern für seiten mit einigen hundert Bildern

**Comment by schuer** [comment]
Ich würde ein Update von aktuell 4/42 auf 10/200 vorschlagen.

**Comment by staabm** [comment]
hast du irgendwelche zahlen dazu? wieviel speicher/lauf-zeit benötigen wir (vorher/nachher)? ich vermute man könnte viel mehr bilder pro run "bauen"

**Comment by tbaddade** [comment]
Wenn das angepasst werden sollte, wäre es gut dafür eine Einstellungsseite zu haben.

**Comment by staabm** [comment]
ich denke wir müssen einfach nur "gute werte finden". 

für den enduser es einstellbar zu haben ist in meinen augen überflüssig.
wenn die werte einigermaßen passen wird man durch custom einstellungen nicht viel erreichen können (ausser es ggf. falsch einzustellen)

**Comment by staabm** [comment]
> Wenn das angepasst werden sollte, wäre es gut dafür eine Einstellungsseite zu haben.

oder anders gesagt: welches ziel verfolgst du wenn du es selbst einstellen willst?

**Comment by schuer** [comment]
@staabm Leider ist das völlig unvorhersehbar und variiert je nach Serverumgebung: Wie groß sind die Bilder + wie lang darf die Skriptlaufzeit sein. Ich fände es unschön, wenn das Addon auf einem schlechten Shared-Hosting in Flammen aufginge.

Sind es kleine Bilder und die Skriptlaufzeit ist eine Minute, könnte man bestimmt auch 100 Bilder mit einem Request generieren. Sind es allerdings sehr große Bilder und die Skriptlaufzeit 30 Sekunden, könnte mein oben genannter Wert von 10 schon fast zuviel sein.

Was die Anzahl der zu generierenden Seiten angeht: Hier könnte man vermutlich locker 1000 oder mehr in einem Request bedienen. Dann läuft nur die Progressbar nicht mehr schick durch ;)

Zum Thema Einstellungsseite: Würde ich auch sehr gerne vermeiden, weil es unnötige Komplexität reinbringt.

**Comment by schuer** [comment]
Nochmal weitergedacht: Das Addon könnte initial versuchen, eigenständig gute Werte zu finden. Indem es z. B. die zu generierenden Bilder nach Größe vorsortiert und probiert, die größten von ihnen so lange zu Paketen zu bündeln, bis es knallt. Und danach den Wert wieder etwas runterpuffert, z. B. -10%.

Also eine Art Selbsttest, den man sogar regelmäßig per Cron ausführen könnte, wenn man wollte. Damit wäre sichergestellt, dass das Addon die höchsten noch praxistauglichen Werte verwendet.

Allerdings etwas aufwendig, oder? Fühlt sich so nach Overengineering an.

**Comment by schuer** [comment]
Weitere etwas vereinfachte Varianten:

1. Beim Erstaufruf die Skriptlaufzeit messen und darauf basierend sinnvolle Schätzwerte für Bilder und Seiten verwenden. Beispiel: Bildgenerierung darf bis zu 3 Sekunden dauern. Dementsprechend 10 Bilder bei 30 Sek. Skriptlaufzeit, 20 bei 60 Sek., usw.
2. Initial recht hohe Werte ansetzen und das Addon reduziert diese eigenständig, wenn es beim Durchlauf »merkt«, dass die Werte zu hoch sind. Damit die Nutzer:innen keine Fehler sehen, könnte das Addon den Durchlauf sogar eigenständig neu anstoßen (ggfls. mit Hinweis).

**Comment by gharlan** [comment]
Brauchen wir überhaupt eine feste Anzahl?
Wahrscheinlich für die ProgressBar von Vorteil, oder?

Ansonsten könnte man es vielleicht auch so machen, dass man einfach rechtzeitig vor Erreichen der Skriptlaufzeit abbricht. Es wäre also pro Aufruf ganz unterschiedlich, wie viele Bildgenerierungen da geschafft werden.

**Comment by schuer** [comment]
Sorry, noch ein Vorschlag. Noch einfacher, allerdings werden die Nutzer:innen diesmal mit einbezogen:
Ein Slider oder Select über dem Startbutton zum Festlegen der »Geschwindigkeit« (so bleibt es halbwegs verständlich). Mini-Erklärung mit dran, dass man bitte langsamer stellen möge, wenn der Warmup nicht durchläuft.

Die dahinterliegenden Werte würde ich fest verknüpfen, so dass der schnellste Modus z. B. den Werten 50/1000 entsprechen könnte, während der langsamste Modus sowas wie die aktuellen 4/42 sein könnte.

**Comment by gharlan** [comment]
Klingt für mich spontan recht gut! (Die Slider-Idee)

**Comment by AWqxKAWERbXo** [comment]
Klingt für mich nach trial & error, wenn's nicht klappt.

**Comment by staabm** [comment]
> @staabm Leider ist das völlig unvorhersehbar und variiert je nach Serverumgebung: Wie groß sind die Bilder + wie lang darf die Skriptlaufzeit sein. Ich fände es unschön, wenn das Addon auf einem schlechten Shared-Hosting in Flammen aufginge.

wir wissen die limits ja, da sie via `ini_get` ausgelesen werden können (sowohl speicher als auch laufzeit).
wir müssen die werte ja nicht so einstellen dass sie das max. ausreizen. dennoch glaube ich dass man deutlich erhöhen kann ohne für ein shared-hosting ein problem zu sein.

> Sorry, noch ein Vorschlag. Noch einfacher, allerdings werden die Nutzer:innen diesmal mit einbezogen:
> Ein Slider oder Select über dem Startbutton zum Festlegen der »Geschwindigkeit« (so bleibt es halbwegs verständlich). Mini-Erklärung mit dran, dass man bitte langsamer stellen möge, wenn der Warmup nicht durchläuft.
> 
> Die dahinterliegenden Werte würde ich fest verknüpfen, so dass der schnellste Modus z. B. den Werten 50/1000 entsprechen könnte, während der langsamste Modus sowas wie die aktuellen 4/42 sein könnte.

diese werte könnte man auch hard-codiert hinterlegen und abhängig von ini_get() speicher/timelimit nehmen (also nicht vom user auszuwählen)

**Comment by staabm** [comment]
vllt könnten wir auch einfach versuchen die limits eines shard hostings auszuloten (z.b. 128mb speicher, 15 sekunden laufzeit) und schauen wie hoch wir mit den chunks gehen können in diesem limit (ich vermute wie gesagt, dass wir viel mehr machen können, selbst bei so kleinem limit)

**Comment by schuer** [comment]
@gharlan Eine variable Anzahl zu verwenden wäre natürlich auch möglich, nur müsste dafür mehr Logik aus dem PHP ins JavaScript wandern, wäre also mit merklichem Aufwand verbunden. Und ja, die Progressbar würde nicht mehr gleichmäßig durchlaufen, aber darauf könnte man sicherlich verzichten.

**Comment by schuer** [comment]
@staabm Ich würde auch lieber in die Richtung gehen wollen, die Werte automatisch unter der Haube anhand von Umgebungsvariablen zu bestimmen, als es den Nutzer:innen zu überlassen.

Vorschlag also nochmal: Wir verwenden `ini_get('max_execution_time')`, um danach unsere Werte zu bestimmen. Speicher kann uns egal sein, glaube ich, weil er nur relevant für die Maximalgröße der Bilder ist, nicht aber für die Geschwindigkeit beim Cache-Generieren. Oder?

Sehr relevant ist die Komplexität der Mediatypes. Skalieren und Nachschärfen kann bei großen Bildern durchaus etwas Zeit benötigen, und wir wissen nicht, was Nutzer:innen sonst noch tun. Manche minifizieren noch im Nachgang oder bringen womöglich Wasserzeichen ein, etc.
— Deshalb: Wollen wir vielleicht damit beginnen, den Bildern 3 Sekunden fürs Cachefile zu geben?

Bei Skriptlaufzeiten von 30/60/90/120 Sek. wären es dann 10/20/30/40 Bilder pro Request. Damit stünde die Progressbar im Worst-Case aber bereits 2 Minuten lang still, deshalb würde ich alle Werte darüber hinaus ignorieren. Was meint ihr?

**Comment by tbaddade** [comment]
Wir hatten letztens die Zeit und den Speicher nach oben gesetzt. Und dennoch brach das warumup ohne Fehlermeldung ab. Das waren ca. 300 Bilder mit 11 Mediatypen (inkl. System).

Mit den Originalbildern von ca. 8MB und mind. 7.000px Seitenlänge ging gleich gar nichts. Ich hatte dann die Bilder lokal herunterskaliert auf max. 4.000px Seitenlänge. Die Bilder waren dann noch max. 4MB groß und auch hier ging warmup nicht in einem Rutsch durch.

Das ist natürlich ein Beispiel was eher seltener vorkommt, aber wir wollten das Bild (Web, Download, etc.) nicht mehrfach im Medienpool haben.

**Comment by schuer** [comment]
@tbaddade Ohne Fehlermeldung abbrechen ist komisch. Eigentlich sollte eine Fehlermeldung kommen. War es R 5.3? Vielleicht sind Anpassungen gemacht worden, die relevant für Cache-Warmup sind, und die wir übersehen haben. Ich habe die Entwicklung leider nicht so genau verfolgt.

Ansonsten: Kantenlänge ist entscheidend, weil jeder Pixel im Speicher gehalten werden muss. Die Dateigröße hingegen ist nur bedingt relevant. Ein einfarbiges PNG mit 10.000 px kann als Datei nur 100 kb groß sein, benötigt im Speicher aber ebenso die vollen 10.000 px, so wie das komplexe Bild einer Blumenwiese, das auf der Platte 8 MB groß ist. Wobei am Ende natürlich beide generierten Bilder wieder auf die Platte müssen, und dann spielen die 8 MB vermutlich auch wieder eine Rolle, weil sie parallel im RAM gehalten werden.
— Wie auch immer, ich wollte nur sagen: Kantenlänge ist der entscheidende Faktor.

TODO für mich: Cache-Warmup mal ausführlich mit großen Bildern in R 5.3 testen und schauen, ob und in welcher Form eigentlich Fehler fliegen.

**Comment by staabm** [comment]
> Sehr relevant ist die Komplexität der Mediatypes. Skalieren und Nachschärfen kann bei großen Bildern durchaus etwas Zeit benötigen, und wir wissen nicht, was Nutzer:innen sonst noch tun. Manche minifizieren noch im Nachgang oder bringen womöglich Wasserzeichen ein, etc.
> — Deshalb: Wollen wir vielleicht damit beginnen, den Bildern 3 Sekunden fürs Cachefile zu geben?

ich denke damit könnte man erstmal anfangen. ist ja dann im endeffekt schon ein vielfaches von dem was wir heute haben.

Aktuell rechnen wir mit 4 images pro request, was bei der Umrechnung dann ja eine "annahme" von max-execution-time von 12 sekunden ist (was sicher in der regel zu wenig ist)

> Bei Skriptlaufzeiten von 30/60/90/120 Sek. wären es dann 10/20/30/40 Bilder pro Request. Damit stünde die Progressbar im Worst-Case aber bereits 2 Minuten lang still, deshalb würde ich alle Werte darüber hinaus ignorieren. Was meint ihr?

falls es wirklich soweit kommt dass der worst case eintritt (also bei 120sek max-exec-time es nicht zu schaffen ist 40 bilder zu genieren) könnte man ja überlegen ob man im js was ändert sodass der fortschrittsbalken nicht stehen bleibt.

einfach mal einstellen und testen...

**Comment by schuer** [comment]
Ich kümmere mich mal drum.

**Comment by staabm** [comment]
@schuer  das zeitlimit kann man übrigens zur laufzeit noch erhöhen[1] falls es probleme macht.. speicherlimit ist durch die Umgebung vorgegeben und zur Laufzeit nicht änderbar

[1] http://php.net/manual/en/function.set-time-limit.php
