### ISSUE TITLE
Kontext für Subpage system.cache-warmup (REX-5.0-Kompatibilität)

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/cache_warmup#6]
In REX 5.0 fehlt der Kontext für `$this` in `system.cache-warmup.php`.

Erst mit REX 5.1 kam die Anpassung »[Subpages immer im richtigen Kontext (package) einbinden](https://github.com/redaxo/redaxo/commit/26cc62a6e9fa3fc70c8c9681e371249fd00ade06#diff-4828640a36fc1334bdf037a02d9b63e1)«.

**Comment by staabm** [comment]
ggf. solltest du einfach min rex 5.1 in der package.yml definieren. 5.0 ist vermutlich noch nicht so weit verbreitet.

**Comment by schuer** [comment]
@staabm Haben wir gestern auch überlegt. Aber der Fix ist ja sehr schlicht, und der Rest des Addons ist auch 5.0-tauglich, insofern ist es sicherlich schöner, 5.0 mit einzubeziehen.
