### ISSUE TITLE
SVGs führen zu Fehler

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/cache_warmup#64]
cache_warmup bricht ab, wenn ein SVG durchlaufen wird. SVG-Dateien sollten dann übersprungen werden...

**Comment by schuer** [comment]
Danke @alexplusde!
Das scheint mir allerdings ein Problem des Media Managers zu sein. Konkret tritt es bei mir auf, sobald die MediaTypen-Effekte angewendet werden (`$media_manager->applyEffects($rex_media_manager_type);` in [media_manager.php#L303](https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/media_manager/lib/media_manager.php#L303)), und auch die normale Ausgabe auf der Website geht in gleicher Form schief, z. B. `index.php?rex_media_type=foo&rex_media_file=bar.svg`.

Kann das jemand bestätigen?

**Comment by AWqxKAWERbXo** [comment]
dübdüdeldü...

https://github.com/redaxo/redaxo/issues/812

**Comment by schuer** [comment]
Kleiner Zwischenstand: Das Problem mit den SVGs sollte aus meiner Sicht nur den **Media Manager 2.3** betreffen. Das ist die aktuelle Version aus dem Installer. In der vorherigen Version 2.2 und dem aktuellen Repo-Stand (2.3.1-dev) tritt das Problem nicht auf. Dort wird ein Fehlerbild generiert (das rote Error-Ding), und Cache-Warmup läuft bis zum Ende durch.

Ich lasse das Ticket noch offen, bis das nächste MM-Release veröffentlicht wurde. Einen Bugfix für MM 2.3 brauchen wir vermutlich nicht. Falls jemand Bedarf daran haben sollte, bitte melden.

**Comment by schuer** [comment]
Im **Media Manager 2.4** der neuen REDAXO-Beta, die heute veröffentlicht wurde, tritt der Fehler ebenso nicht mehr auf.
