### ISSUE TITLE
Hilfreiche Fehlerausgabe implementieren

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/cache_warmup#66]
Wenn Cachewarump einen Fehler erzeugt, wird einem ein Link angezeigt, der zum fehlerhaften Artikel / Bild führen soll. Klickt man auf den Link, passiert nichts, da dieser falsch aufgebaut zu sein scheint.

`http://domain.de/redaxo/index.php?page=cache_warmup/generator&images=11.rex_mediapool_maximized,11.rex_mediapool_preview,10.art_image,10.download,10.gallery-flexslider,10.gallery-thumbnail,10.mblockslide,10.product,10.product-acetum-label,10.product-weingut-label,10.rex_mediabutton_preview,10.rex_medialistbutton_preview,10.rex_mediapool_detail,10.rex_mediapool_maximized,10.rex_mediapool_preview,8.art_image,8.download,8.gallery-flexslider,8.gallery-thumbnail,8.mblockslide,8.product,8.product-acetum-label,8.product-weingut-label,8.rex_mediabutton_preview,8.rex_medialistbutton_preview,8.rex_mediapool_detail,8.rex_mediapool_maximized,8.rex_mediapool_preview,7.art_image,7.download,7.gallery-flexslider,7.gallery-thumbnail,7.mblockslide,7.product,7.product-acetum-label,7.product-weingut-label,7.rex_mediabutton_preview,7.rex_medialistbutton_preview,7.rex_mediapool_detail,7.rex_mediapool_maximized,7.rex_mediapool_preview,6.art_image,6.download,6.gallery-flexslider,6.gallery-thumbnail,6.mblockslide,6.product,6.product-acetum-label,6.product-weingut-label,6.rex_mediabutton_preview`

**Comment by schuer** [comment]
Der Link passt schon, nur unterdrückt der Media Manager den Output (https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/assets/js/cache-warmup.js#L399-L402), so dass du vermutlich eine weiße Seite siehst, wenn du dem Link folgst. Was genau schief läuft kann Cache-Warmup leider nicht mitteilen, aber mindestens eins der aufgeführten Bilder sorgt für den Fehler.

**Comment by schuer** [comment]
Welche Fehlermeldung wird denn eigentlich im Warmup-Popup ausgegeben?

**Comment by AWqxKAWERbXo** [comment]
Wäre es dann nicht sinnvoll, die Dateinamen einfach auszugeben, statt in einem Link?

Fehlermeldung kann ich dir nicht mehr sagen, aber der Fall trat öfter auf...

**Comment by schuer** [comment]
Ich bin mir gerade nicht sicher, wie detailiert und hilfreich wir eine Fehlerausgabe hinbekommen. Denn eigentlich gibt es keine richtige Fehlerbehandlung beim Generieren der Cachefiles, die eindeutig beinhaltet, was eigentlich schief gegangen ist. Das liegt daran, dass der Media Manager im Fehlerfall bewusst nicht abbrechen möchte — dann wäre die Website kaputt —, sondern ein Fehlerbild zurückgibt.

Was wir aber sicherlich machen können, und das schriebst du ja bereits, ist, die betroffenen Dateien namentlich aufzulisten, anstatt wie bisher nur einen Link auszugeben.

(Ich habe aktuell nur wenig Zeit für REDAXO-Themen. Falls jemand Zeit und Lust hat, das Feature umzusetzen: Gerne, danke!)

**Comment by schuer** [comment]
Wird im Zuge von #81 behoben werden.
