### ISSUE TITLE
Template beim Generieren der Artikelcaches mit einbeziehen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/cache_warmup#71]
Siehe Diskussion hier: FriendsOfREDAXO/demo_base#44

**Comment by schuer** [comment]
Hat jemand einen Vorschlag, wie wir das umsetzen können?

**Comment by staabm** [comment]
GetArticeTemplate() statt getArticle() verwenden

**Comment by schuer** [comment]
Haha, das ist ja zu einfach. `GetArticeTemplate()` kannte ich noch nicht, scheint auf Anhieb prächtig zu funktionieren. Ich sah mich im Vorfeld schon wild bootstrappen, um das Template mit rein zu kriegen und nicht alles kaputt zu machen :)
Danke für den Hinweis, @staabm.
