### ISSUE TITLE
YForm-Felder aktualisieren: `be_media`, `be_medialist`, `mediafile`

### ISSUE THREAD

**Issue by anveno** [FriendsOfREDAXO/cache_warmup#74]
Eventuell kann man in der Hilfe Datei noch ergänzen das bei yform nur in "be_media" und "be_medialist" gesucht wird; nicht z.B. in mediafile - dort liegen bei mir die Bilder :)

selector.php / Zeile 56:
`find images in yforms (be_media, be_medialist)`

**Comment by schuer** [comment]
Danke für den Hinweis! Ich hatte gar nicht mitbekommen, dass es `be_medialist` gar nicht mehr gibt. Und `mediafile` ist irgendwie auch an mir vorbeigegangen ;)
