### ISSUE TITLE
Fehler über https

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/cache_warmup#77]
Cache_Warmup funktioniert bei mir nicht wenn ich das Redaxo-backend via **https** aufrufe.
In Chrome kommt ein **"TOO MANY REDIRECTS"** Fehler, in Firefox kam ein **"301 MOVED PERMANENTLY".** Über http funktioniert es normal. Keine Ahnung ob das was mit Serverkonfiguration zu tun hat oder mit dem Addon.

**Comment by schuer** [comment]
@fietstouring Das wirkt eher so, als ob beim Versuch, http-Anfragen auf https umzuleiten, etwas schief geht. Cache-Warmup selbst macht eigentlich keine Angaben über das Protokoll, so dass ich den Fehler woanders vermute. Ich schaue es mir jedenfalls mal an, danke für den Hinweis!

**Comment by fietstouring** [comment]
Hier noch eine Meldung von Chrome, die Bestätigung der Meldung ändert allerdings nichts.

![bildschirmfoto 2017-10-03 um 17 48 17](https://user-images.githubusercontent.com/1846849/31134729-47831580-a863-11e7-8377-f115bcf8554a.png)

**Comment by schuer** [comment]
Hast du in der `redaxo/data/core/config.yml` die Angabe bei `server: ` mit https ausgezeichnet?

Und kannst du bitte einmal in den Quelltext der Seite schauen, nach `cache-warmup.js` suchen und sagen, ob die Datei mit http oder https vorne aufgerufen wird? Danke!

**Comment by fietstouring** [comment]
Ja wenn ich die ganze Seite auf https umstelle, dann läuft es normal.

**Comment by schuer** [comment]
Ich bin leider noch nicht dazu gekommen, mir das näher anzuschauen. Aber um die Sache weiter einzugrenzen: Könntest du mal eine kleine Anpassung testen, und diese Zeile auskommentieren:

https://github.com/FriendsOfREDAXO/cache_warmup/blob/master/boot.php#L45

Sie sorgt dafür, dass REDAXO zum Generieren der Cachefiles in den Frontend-Modus geschickt wird. Ich weiß gerade nicht aus dem Stehgreif, was da alles dranhängt, aber es könnte u. U. dafür sorgen, dass zum Inkludieren der Assets http verwendet wird, obwohl du im https-Backend bist.
Danke!

**Comment by schuer** [comment]
Ich habe das jetzt mal hin und her getestet mit SSL und ohne. Am AddOn scheint es nicht zu liegen, sondern vermutlich wirklich an deinem Setup, und dass dort Redirects stattfinden und/oder Ressourcen mittels http eingebunden werden.

Bei Bedarf gerne nochmal öffnen.

**Comment by fietstouring** [comment]
Sorry, hab ganz drauf vergessen das nochmal zu testen... Scheint aber nicht so wichtig gewesen zu sein... Danke

Am 29. Mai 2018 20:41:52 MESZ schrieb "Dirk Schürjohann" <notifications@github.com>:
>Ich habe das jetzt mal hin und her getestet mit SSL und ohne. Am AddOn
>scheint es nicht zu liegen, sondern vermutlich wirklich an deinem
>Setup, und dass dort Redirects stattfinden und/oder Ressourcen mittels
>http eingebunden werden.
>
>Bei Bedarf gerne nochmal öffnen.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/FriendsOfREDAXO/cache_warmup/issues/77#issuecomment-392891600

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
