### ISSUE TITLE
Umgang mit Fehlern anpassen, Report erstellen statt Abbruch

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/cache_warmup#81]
Aufgrund des Feedbacks in #66, #80 und #82 denke ich inzwischen, dass die Fehlerbehandlung wirklich angepasst werden sollte:

1. Warmup läuft grundsätzlich durch und bricht nicht mehr mit Fehlern ab.
2. Warmup merkt sich Vorkommen von Bildern, die nicht richtig generiert werden konnten (Speicherüberlauf) und auch Seiten, die nicht generiert werden konnten (z. B. aufgrund von `exit;` im Template), und es gibt nach dem Durchlauf einen Report aus.

Problem bei Punkt 2 könnte sein, dass Warmup mit jedem Request mehrere Seiten und Bilder generiert, und dass wir u. U. nicht sinnvoll herausfinden können, welche davon Fehler produziert haben. Falls dem so ist, müssten wir einen allgemeinen Report ausgeben im Sinne von _»Einige Bilder konnten nicht verarbeitet werden.«_.

Ggfls. beachten: Bedienung über die Konsole, und falls dafür ein bestimmtes Verhalten sinnvoll ist, etwa beim Report. Aber darum wird sich vermutlich eher @gharlan oder jemand anderes später kümmern, und es ist für dieses Ticket erstmal nicht relevant.

**Comment by schuer** [comment]
Ein Update, ich hatte es heute schon im Slack angesprochen:

✅ Cache-Warmup läuft nach meinen (lokalen) Anpassungen bis zum Ende durch, auch wenn unterwegs Fehler auftreten, sei es durch zu wenig RAM für die Bildgenerierung oder aufgrund von PHP exceptions im Code von Templates oder Modulen.
— Das ist prima, und so wollten wir es haben.

⚠️ Allerdings gibt es ein Problem mit dem **Report** am Ende: Wie bereits vermutet kriegen wir nicht ohne weiteres raus, welche Bilder oder Seiten betroffen sind, denn Cache-Warmup generiert mit jedem Request eine Vielzahl von Objekten (bis zu 1000 Seiten und bis zu 50 Bildern). Der ursprüngliche Plan, am Ende nochmal einzeln durch die betroffenen Objekte zu laufen, hat sich für mich als nicht sehr überzeugend rausgestellt, denn es wird in vielen Fällen zu lange dauern und feuert unnötig viele Requests auf den Server. Natürlich kann es gut gehen, und es werden z. B. nur 50 Requests im Anschluss notwendig, um die fehlerhaften Objekte zu prüfen. Wenn es aber schlecht läuft, können es auch 10.000 oder mehr Requests sein, und die sollten wir nicht abfeuern, finde ich. Das würde viele Stunden dauern und den Webserver unnötig belasten.
— Das Konzept scheint nicht robust zu sein.

👎 Nun könnte man **auf den detailierten Report verzichten** und zumindest die Requests ausgeben, die Fehler produziert haben. Aber auch das finde ich weder schön noch hilfreich: Stellt euch vor, ihr erhaltet nach dem Warmup-Vorgang eine Info, dass eins der 50 Bilder nicht generiert werden konnte oder manche der 1000 Seiten. Und dann werden all diese IDs auch noch ausgegeben, ihr habt also über Tausend Zahlen im Browserfenster.
— Diese Möglichkeit fällt für mich kategorisch aus. Wenn ein Report kommt, dann sollte er detailiert sein.

👍 Was möglich ist, aber in einem anderen Kontext, ist ein detailierter **Report innerhalb der Konsole**. REDAXO kann ja seit einiger Zeit Konsolenbefehle, und auch Cache-Warmup soll demnächst über die Konsole bedienbar sein. Und hier haben wir dann auch kein Problem mit den Requests, sondern können problemlos alle zu cachenden Objekte einzeln durchlaufen. Sprich: Hier ist ein detailierter Report problemlos möglich.

👉 Außerdem noch zu bedenken: Dass Fehler beim Warmup aufkommen, sollte hoffentlich eher selten vorkommen. Denn Fehler bedeuten, dass die Website nicht richtig funktioniert, und sowas sollte normalerweise schon während der Entwicklung festgestellt werden. In den meisten Fällen sollte Cache-Warmup also fehlerfrei durchlaufen und ist dann am Ende auch in der Lage, zumindest den Positiv-Report liefern: Cache vollständig generiert.

**Mein Fazit aus all den Gedanken ist nun:**

1. Wir sollten bei der Bedienung über die Weboberfläche **keinen Report** erstellen, denn es ist nicht zuverlässig möglich. Stattdessen ein Hinweis, dass der Cache generiert wurde, allerdings nicht vollständig, und eine Info dazu, wie man mit dem Problem nun umgehen sollte.
2. Wir sollten einen **Report innerhalb der Konsole** implementieren. Das klappt problemlos und ist sehr hilfreich für Developer, um die Website auf Funktion zu prüfen.

**Was meint ihr?**

**Comment by bloep** [comment]
> Wie bereits vermutet kriegen wir nicht ohne weiteres raus, welche Bilder oder Seiten betroffen sind

Eine Variante wäre noch, vor dem Durchlaufen einer Seite / eines Bildes Informationen (bspw. den `filename` oder `article_id`) in der Datenbank oder Cache zu "merken". Im Anschluss könnte man auslesen welche Objekte Probleme bereitet haben. Dies würde sich aber bei einer großen Anzahl an Objekten negativ auf die Laufzeit auswirken...

**Comment by AWqxKAWERbXo** [comment]
Wie würde man vorgehen, wenn man den Fehlerreport losgelöst vom Cache Warmup betrachtet? Bspw., indem die Anforderung erweitert wird zum "Website Check". Also eine Art Wartungsfunktion, bei der maschinell überprüft wird, ob das Redaxo-Frontend intakt ist, oder eine Seite / ein Medium Probleme macht. Wie würde man dann bei 20.000 Seiten vorgehen?

Ansonsten bitte ich darum, auch hier wieder die Nutzer zu berücksichtigen, die sich noch nicht mit der Console auseinandergesetzt haben, es ihnen möglichst leicht zu machen. (Ich persönlich benutze Cache Warmup schon seit weit über einem halben Jahr nicht mehr, weil mir das Finden der Fehlerquelle oft nicht möglich war.)

edit: verstehe übrigens nicht, warum aus dem Block von 50 Bildern sich nicht das Medienobjekt melden kann, das gescheitert ist.

**Comment by schuer** [comment]
@alexplusde 
> Wie würde man vorgehen, wenn man den Fehlerreport losgelöst vom Cache Warmup betrachtet? 

Vermutlich würde man alle einzelnen Ressourcen der Website einmal anfragen und prüfen, ob das gewünschte Ergebnis geliefert wird. Bei Seitenaufrufen das Markup, bei Bildern das generierte Bild und bei sonstigen Ressourcen das zu erwartende Ergebnis. Wenn es keine schlichte Website ist, kann es sein, dass man noch diverse Kontexte beachten muss: Sessions, GET/POST, IP, Client, Zeit des Aufrufs, Ort des Aufrufs, usw.

> edit: verstehe übrigens nicht, warum aus dem Block von 50 Bildern sich nicht das Medienobjekt melden kann, das gescheitert ist.

Die Bilder werden serverseitig im REDAXO-Kontext generiert. Wenn dabei was schiefgeht, weil etwa zu wenig RAM verfügbar ist oder die maximale Scriptlaufzeit erreicht wurde, bricht der gesamte Prozess ab, ohne dass du ihn sinnvoll auffangen kannst. Deshalb wird der Generator von außen mittels JS (AJAX) angesprochen und die zu generierenden Dateien als Parameter übergeben. Wir bündeln dabei Bilder und Seiten — abhängig von den vorher ermittelten Serverparametern, also beispielsweise die schon genannten 50 Bilder und 1000 Seiten auf einem leistungsfährigen Server — und lassen sie in einem Rutsch generieren. Als Ergebnis kriegen wir aber nur mit, ob es geklappt hat, oder ob etwas schief gegangen ist. Und wenn etwas schief gegangen ist, können wir nicht sagen, bei welchem Objekt, denn das Ergebnis liefert keine Details.

Details würde man nur erhalten, wenn man jedes Objekt einzeln generieren ließe. Das würde allerdings einen Haufen von AJAX-Requests erforderlich machen, und die dauern dann entsprechend lange. Die Konsole hingegen würde ja nicht von außen feuern, sondern befindet sich auf dem Server selbst, deshalb könnte sie problemlos und ohne Requestzeiten jedes einzelne Objekt generieren lassen.

**Comment by AWqxKAWERbXo** [comment]
Kann man nicht eine Teilantwort ausgeben? Also immer, wenn ein Medium bearbeitet wurde, die Rückantwort ergänzen?

**Comment by schuer** [comment]
Im aktuellen Setup nicht. Aber vielleicht können wir eine weitere cURL- oder Socket-Ebene implementieren:

`Client ---(AJAX)---> PHP Dispatcher ---(cURL/Socket)---> PHP Generator`

Hat jemand Erfahrungen/Meinungen dazu?

**Comment by staabm** [comment]
Kann man den angesprochenen fehler serverseitig mit try/ctach nicht abfangen?

Oder wird ein error im serverlog auftauchen?

**Comment by schuer** [comment]
@staabm Fehler im Code schmeißen einen Whoops, mir scheint, das kann man aktuell nicht abfangen. Vielleicht kannst du als Core-Mensch mal einen Blick drauf werfen, falls du Zeit und Lust hast.

Generell haben wir allerdings gerade das Problem, dass verschiedene REDAXO-5-Versionen unterschiedlich reagieren. Mit `rex_media_manager::create()` (MM 2.3.0) können wir die Bildgenerierung besser abfangen, indem wir den Rückgabewert prüfen: Kommt nichts zurück, ist was schief gegangen, hat es geklappt, kommt ein Medienobjekt zurück. Der ältere Fallback hingegen liefert keinen Rückgabewert, was es etwas kompliziert macht. Zudem fliegen dort in bestimmten Situationen 500er, wenn der RAM nicht ausreicht. Und um es noch verwirrender zu machen, liefert der alte Fallback in _neuen_ REX-Versionen offenbar durchgängig einen Whoops.

Ich bin gerade etwas unschlüssig, wie wir aus der Nummer rauskommen wollen.

**Comment by staabm** [comment]
Hast du einen konkreten stacktrace/error fall den ich anschauen soll?

Bzgl problem mit den unterschiedlichen APIs -> am einfachsten wäre die mindestversion anheben

**Comment by schuer** [comment]
@staabm Nein, ich habe leider nichts zum anschauen, sondern habe nur lokal dran rumgebaut und beispielsweise ein `exit;` oder irgendeinen Zeichensalat ins Template geschrieben. Ist aber gar nicht schlimm, denn ich habe schon wieder ein Update zum Thema:

__Update:__ Ich habe jetzt nochmal verschiedene Situationen durchgespielt:
1. Fehler im Code von Templates oder Modulen produzieren einen Whoops, den wir (aus meiner Sicht) nicht abfangen können.
2. Fehler bei der Bildgenerierung im _alten Media Manager_ können wir ebenso nicht abfangen, denn der Code ist so aufgebaut, dass die Cache-Generierung fest mit der Ausgabe des Bildes verknüpft ist. Heißt: Das Bild kommt raus, und der Prozess wird beendet. Keine Chance für uns, danach einzuhaken.
3. Allein Fehler bei der Bildgenerierung im _neuen Media Manager_ können wir abfangen. Hier kommt ein Objekt zurück, wenn es geklappt hat, oder keins, wenn was schiefgegangen ist. Und es fliegt keine Exception. Damit könnten wir arbeiten!

**Fazit:** Aufgrund von 1. und 2. scheint mir, dass wir zurück am Anfang sind: Wir kriegen nicht mit, welche Cachefiles nicht generiert werden konnten und ein Report ist damit nicht sinnvoll möglich.

Habt ihr weitere Ideen oder Anmerkungen?

**Comment by staabm** [comment]
Wäre es ein problem wenn men den report nur mit dem neuen Mediamanager bereitstellt und bei älterem ein update hinweis/empfehlung gibt?

**Comment by schuer** [comment]
Update zu 3.: Es fliegt leider doch ein Fehler, das hatte ich übersehen: Allowed memory size of x bytes exhausted. Steht auch im Syslog. Und natürlich bricht damit auch der Prozess ab, ohne dass wir ihn wieder einfangen könnten.

@staabm Es wäre kein Problem gewesen, hat sich gerade mit meinem Update nur leider erledigt.

**Comment by schuer** [comment]
Die Erkenntnisse aus diesem Issue sind sicherlich inzwischen obsolet. Es gibt Pläne, die Frontend-App grundlegend zu überarbeiten, und dieses Issue kann dabei nicht helfen, deshalb schließe ich hier.
