### ISSUE TITLE
Diverse Abbrüche

### ISSUE THREAD

**Issue by frood** [FriendsOfREDAXO/cache_warmup#82]
Krieg das Ding nicht zum laufen ... schade, die Idee ist wirklich super!
Aber ohne bessere Fehlerausgabe (wie schon mehrmals erwähnt) ist kaum rauszufinden, was nun wirklich stört. 
Trotzdem mal einige Vermutungen und Anmerkungen ... vielleicht hilft es beim debugging:
- bei meinem 'not found'-Artikel hängt es
- Seiten mit Modul, welches jquery enthält
- bei meheren Domains (über yrewrite)
- bei Ajax-Content

Wenn ich mal etwas mehr Zeit habe werde ich mal genauer auf die Suche gehen .....

**Comment by schuer** [comment]
Danke für die Meldung! Und schade natürlich, dass du so viele Abbrüche hast. Früher hatte Cache-Warmup mal nur Inhalte generiert, ohne Templates drumrum. Als die Templates hinzugekommen sind, hat sich die Fehleranfälligkeit erhöht, und in der Praxis wäre es jetzt wirklich sinnvoll, Cache-Warmup grundsätzlich bis zum Ende durchlaufen zu lassen, um am Ende einen Report zu erstellen. (Zugehöriges Issue ist #81.)

**Comment by schuer** [comment]
Wird im Zuge von #81 behoben werden.
