### ISSUE TITLE
Funktioniert der noch?

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/cache_warmup#87]
Ich habe in letzter Zeit mehrfach auf unterschiedlichen Servern versucht das Addon zu nutzen und jedesmal kam die Meldung, dass ein Fehler aufgetreten ist ... mit einem Link zu einer Fehlerseite, die aber wenn ich sie anschauen will komplett weiss ist... Hab die neuste Version und das neuste Redaxo.

**Comment by schuer** [comment]
Grundsätzlich sollte es funktionieren, ja. Wenn es mal nicht funktioniert, ist meist zu wenig RAM für die Bildgenerierung die Ursache. Und dann sind zwei Dinge beim Warmup etwas ungeschickt:

1. Warmup bricht ab. Schöner wäre, wenn es trotz Fehlern bis zum Ende durchliefe und danach Bescheid gäbe, dass unterwegs was geklemmt hat.
2. Die Fehlerseite ist nicht hilfreich, enthält keine sinnvolle Ausgabe. Sie hat aktuell nur die Funktion, dass man an der URL sehen kann, welche Gruppe von Objekten nicht generiert werden konnte. Schöner wäre eine hilfreiche Fehlerseite.

Beides wird sich mal mit #81 erledigt haben, aber aktuell gibt es kaum Zeit und Motivation dafür.

_(Ich schließe mal direkt. Falls noch was konkretes ist, gerne wieder öffnen.)_
