### ISSUE TITLE
Bedienung über Konsole implementieren

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/cache_warmup#89]
![kapture 2019-01-06 at 10 44 07](https://user-images.githubusercontent.com/1297466/50739832-b26a3a80-11e5-11e9-885c-00b7142ed54a.gif)

Im Branch `console` gibt es bereits einen recht fortgeschrittenen Stand. Allerdings wird noch die Fehlerbehandlung und der anschließende Report benötigt.

## Ziele

- Alle Fehler und Exceptions abfangen, so dass der Warmup-Prozess in jedem Fall bis zum Ende durchläuft (Ggfls. bietet sich dafür symfonys [Process-Komponente](https://symfony.com/doc/current/components/process.html) an, um den Cache in einem Subprozess zu generieren)
- Im Falle von Fehlern soll am Ende ein Report generiert werden, der aufzeigt, welche Cachefiles nicht generiert werden konnten.

## Typische Fehlerfälle, und wie man sie zwecks Debugging nachstellt

- **Zu wenig RAM, um Thumbnails zu generieren.** Kann sehr einfach nachgestellt werden, in dem ein beliebiges Bild mit sehr vielen Pixeln (etwa 15000x15000, kann auch nur ein einfarbiges PNG sein. Die Pixelwerte sind allein entscheidend für den RAM.) in den Medienpool geladen und dann in einem beliebigen Artikel oder Metadaten verwendet wird.
- **Fehler in Templates oder Modulen.** Zum Nachstellen einfach irgendeinen Murks in ein Template schreiben.
- ~**Skriptlaufzeit überschritten.** Zum Nachstellen am besten `max_execution_time` des Servers auf einen geringen Wert stellen (etwa 10 Sekunden) und die Cache-Warmup-Config so anpassen, dass absurd viele Cachefiles pro Request erstellt werden. Dafür wie hier beschrieben einfach mit `$throttle = 1000;` (1000%) arbeiten: https://github.com/FriendsOfREDAXO/cache_warmup#request-timeout-408~ _(Korrektur: Kommt in der Konsole nicht vor, ist nur ein clientseitiges Problem beim Warmup im REDAXO-Backend)_

Ich arbeite zum Debuggen meist mit der [Basis-Demo](https://github.com/FriendsOfREDAXO/demo_base) oder der [Onepage-Demo](https://github.com/FriendsOfREDAXO/demo_onepage), damit ich ein paar Inhalte im REDAXO habe, mit denen ich rumspielen kann.

**Comment by schuer** [comment]
Es wäre großartig, wenn jemand die Fehlerbehandlung umsetzen könnte. Mir fehlt dafür die Erfahrung mit solchen PHP-Prozessen. Ich kann aber gerne am Ende den Report erstellen, wenn gewollt.

Ping an @staabm @gharlan @bloep, aber natürlich sollen sich auch alle anderen angesprochen fühlen, die sich die Implementierung zutrauen. 👍

**Comment by gharlan** [comment]
> * Skriptlaufzeit überschritten.

In der console stellen wir die max_execution_time immer auf unendlich, dieses Problem sollte es also in der Console nicht geben.
https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/console.php#L3

**Comment by schuer** [comment]
Das Thema Konsole wird vermutlich nicht weiter verfolgt werden; zumindest von mir nicht. Wer möchte, kann gerne wieder öffnen und/oder dran arbeiten.

Die Generierung von Artikeln innerhalb der Konsole ist problematisch, weil der Kontext ein anderer ist als beim Aufruf durch den Browser. Das betrifft Sessions und ggfls. manche andere Stellen innerhalb REDAXOs. Das eigentliche Ziel, zu prüfen, ob alle Artikel sauber ausgeliefert werden, kann damit nicht sinnvoll erreicht werden.

Beim Generieren von Bildern hätte die Konsole merkliche Vorteile gegenüber dem Aufruf im Browser, weil sie nicht in Skriptlaufzeiten läuft und keine Requests von außen abgeschickt werden müssen. Damit wäre auch die Fehlerbehandlung merklich einfacher, weil jedes Bild einzeln generiert wird und das Ergebis geprüft werden kann.
Aber auch hier ist der Kontext in der Konsole ein anderer als beim Aufruf im Browser, und mir persönlich wäre wichtiger, dass letzterer erfolgreich durchläuft und z. B. nicht an zu wenig RAM scheitert.

Ich möchte lieber am Frontend arbeiten und die Konsole nicht weiter verfolgen.
