### ISSUE TITLE
Fehlermeldung bei Multi-Domain-Site mit yrewrite

### ISSUE THREAD

**Issue by helpy** [FriendsOfREDAXO/cache_warmup#93]
Ich habe yrewrite mit zwei Domains (www.example.com und sub.example.com) eingerichtet.
Melde ich mich im Backend nur mit www.example.com/redaxo an, dann wird eine Fehlermeldung ausgegeben:

> **Verdammt, etwas ist schief gelaufen!**
> 
> Beim Erzeugen des Caches ist ein Fehler aufgetreten. Details befinden sich auf der Fehlerseite. Wir freuen uns über jede Mithilfe, die Qualität des Addons zu verbessern, indem Fehler bei Github gemeldet werden. Vielen Dank!
> 
> (0) → Link zur Fehlerseite

Der Link zur Feherlseite führt zur Startseite der zweiten Domain sub.example.com.

Wenn ich mich aber vorher bei beiden Domains unter Redaxo anmelde (www.example.com/redaxo und sub.example.com/redaxo), dann läuft die Cache-Generierung ohne Fehler durch.

NACHTRAG:
Nach weiteren Tests hat sich herausgestellt, dass die Cache-Generierung nur von sub.example.com aus ohne Fehler durchläuft. Der Aufruf von www.example.com funktioniert nicht.

**Comment by schuer** [comment]
@helpy Ich kann dein Problem hier lokal leider nicht nachvollziehen. Habe zwei Domains angelegt, `test1.local` und `test2.local`, die mit einem aktuellen REDAXO 5.6.2 und der Basis-Demo laufen. Dazu habe ich ein aktuelles YRewrite installiert und so konfiguriert, dass `test1` die Demo auf Deutsch zeigt, `test2` die Demo auf Englisch. Cache-Warmup funktioniert problemlos auf beiden Domains, egal ob der Nutzer auf der jeweils anderen parallel eingeloggt ist oder nicht.

* Welche Versionen von REDAXO, YRewrite und Cache-Warmup nutzt du?
* Siehst du im Warmup-Popup in der Adresszeile jeweils die richtige Domain in der URL?
* Magst du in `/assets/addons/cache_warmup/js/cache-warmup.js` in Zeile 4 mal `DEBUGMODE` auf true setzen, den Warmup neu starten und im Popup die Fehlerkonsole öffnen (Mac: CMD + alt + i, Windows: Strg + alt + k). Dort sollten nun diverse Debug-Infos ausgegeben werden, und vielleicht siehst du dort anhand der Requests, dass die jeweils falsche Domain angefragt wird. Kannst ja den spannenden Teil mal hier ins Issue kopieren.

Danke!

**Comment by schuer** [comment]
Achso, noch eine Frage: Fliegt der Fehler beim Generieren von Bildern oder von Seiten? Das siehst du an der URL des Links zur Fehlerseite. Der Parameter am Ende beginnt entweder mit `?images=` oder mit `?pages=`. Und wie ist dein YRewrite eingestellt, zeigen deine Domains auf unterschiedliche Sprachen, so wie in meinem Setup?

**Comment by helpy** [comment]
> Welche Versionen von REDAXO, YRewrite und Cache-Warmup nutzt du?
* Redaxo 5.6.2
* YRewrite 2.3
* Cache-WarmUp 3.3.1

> Siehst du im Warmup-Popup in der Adresszeile jeweils die richtige Domain in der URL?

Ja.

> Achso, noch eine Frage: Fliegt der Fehler beim Generieren von Bildern oder von Seiten? 

Ich nehme an, dass das beim Generieren der Bilder passiert, da die Fortschrittsanzeige der Seiten (1 von 26, 2 von 26, ... 26 von 26) bis zum Ende durchläuft, aber die Fortschrittsanzeige der Bilder nicht mehr angezeigt wird. Das ist aber nur eine Vermutung. Fehler könnte ja auch bei der letzten Seite auftreten.

Seltsam finde ich folgende Fehlermeldung:
==> `(0)`  --> Link zur Fehlerliste

Der Link zur Fehlerliste sieht wie folgt aus:
`https://www.meine-domain.tld/redaxo/index.php?page=cache_warmup/generator&pages=1.1,2.1,3.1,4.1,7.1,10.1,11.1,13.1,15.1,16.1,17.1,21.1,23.1,24.1,25.1,26.1,27.1,28.1,29.1,30.1,32.1,33.1,34.1,36.1,38.1,41.1`

> DEBUG Modus:

Da gibt es verschiedene Warnungen/Fehlermeldungen:

==> Warnungen:
```
  Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://sub.meine-domain.tld/. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).
  Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://sub.meine-domain.tld/. (Grund: CORS-Anschlag schlug fehl).
```

==> Fehlermeldung: 
```
content: inject content_info to content cache-warmup.js:13:35
content: inject button_again to footer cache-warmup.js:13:35
content: inject title_error to title cache-warmup.js:13:35
content: inject icon_error to icon cache-warmup.js:13:35
> Error: cache-warmup.js:418:43
  generate/</</<   https://www.meine-domain.tld/assets/addons/cache_warmup/js/cache-warmup.js:418:43
  i                https://www.meine-domain.tld/assets/core/jquery.min.js:2:27146
  fireWith         https://www.meine-domain.tld/assets/core/jquery.min.js:2:27914
  z                https://www.meine-domain.tld/assets/core/jquery.min.js:4:12082
  c/<              https://www.meine-domain.tld/assets/core/jquery.min.js:4:15594
content: inject content to text
```

**Comment by helpy** [comment]
Aaaah ... ich habe die Ursache gefunden.

Ich habe auf einer Seite der Hauptdomain "www.meine-domain.tld" das Modul "05-1 Artikelweiterleitung" aus dem Addon "D2U Helper" in Verwendung. Der Artikel, auf den weitergeleitet wird, befindet sich in der Sub-Domain. Wenn ich die Weiterleitung herausnehme, dann funktioniert alles!

Ob, das nun ein Fehler oder eine Einschränkung ist, kann ich nicht beurteilen.
Das überlasse ich Euch, wie Ihr das einordnet.

**Comment by helpy** [comment]
> Und wie ist dein YRewrite eingestellt, zeigen deine Domains auf unterschiedliche Sprachen, so wie in meinem Setup?

Nein! Keine unterschiedlichen Sprachen.

Es gibt eine Hauptdomain (Musikverein) und eine Sub-Domain für eine Gruppe von Musikern, wo Termine für diese Gruppe, Noten, MP3s und sonstiges verteilt werden. In der Hauptdomain gibt es eine Kategorie mit einer Weiterleitung (Modul Artikelweiterleitung) im Startartikel, damit ich über das Menü von der Hauptseite zur Sub-Domain komme.

Ich bin aber dabei, eine andere Lösung auszuprobieren ...

**Comment by helpy** [comment]
ACH ja! 

@schuer 
Vielen Dank für Deine Fragen!
Dadurch konnte ich die Ursache lokalisieren :-)

**Comment by schuer** [comment]
Gut, dass du den Fehler gefunden hast! Ich würde dann hier schließen, denn das CORS-Problem aufgrund der unterschiedlichen Domains ist kein Bug des AddOns und kann hier nicht behoben werden. Zudem wird das AddOn gerade dahingehend umgebaut, dass es nicht mehr mit Fehlern abbricht, sondern immer vollständig durchläuft und am Ende eine Info zeigt, ob unterwegs was schiefgegangen ist.

**Comment by helpy** [comment]
Vielen Dank Dirk,
für den kleinen Ausblick.

Ich habe das mit der Weiterleitung nun anders gelöst und das Addon läuft jetzt durch.

Gruß aus Niederbayern,
Guido
