### ISSUE TITLE
YRewrite: Call to a member function getTitle() on null

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/cache_warmup#95]
![image](https://user-images.githubusercontent.com/330516/44837366-c1d6e700-ac39-11e8-856e-0fb929ae4eb5.png)

**Comment by schuer** [comment]
Hey @olien, die Meldung kommt als Whoops, wenn du Cache-Warmup laufen lässt, dieses abbricht und du dann den Link auf die Fehlerseite aufrufst?

**Comment by schuer** [comment]
@olien? Ist das noch aktuell? Und war es nicht eher ein YRewrite-Fehler, den Cache-Warmup lediglich aufgedeckt hat? ;)

**Comment by AWqxKAWERbXo** [comment]
Definitiv kein cache_warmup-Fehler, sondern eine Fehlkonfiguration von oder Fehlfunktion in YRewrite.

**Comment by schuer** [comment]
Danke, dann schließe ich hier, und du machst wieder auf, falls es doch noch akut ist und mit Cache-Warmup zu tun haben könnte, okay Olli?
