### ISSUE TITLE
Probleme mit YRewrite und Multi-Domain-Setup

### ISSUE THREAD

**Issue by maxmoeller** [FriendsOfREDAXO/cache_warmup#96]
Nach Update auf Version 3.3.1

Erhalte ich beim Klicken auf "Cache jetzt gen.." => "Verdammt, etwas ist schief gelaufen! ...."

nginx error.log

```
2018/09/25 11:46:53 [error] 20605#20605: *422 FastCGI sent in stderr: "PHP message: Undefined variable: item
PHP message: Undefined variable: item
PHP message: Undefined variable: item
PHP message: Undefined variable: item
......
```

Re-Install wurde durchgeführt
De-Install + Löschen + Neu-Install wurden durchgeführt

Gleiche Resultat

Downgrade auf 3.2 => Gleiche Resultat im Log

Versionen:
REDAXO  5.6.2
PHP 7.0.31
MySQL 5.5.5-10

**Comment by staabm** [comment]
gibts im systemlog bissl mehr infos (wo die notice auftaucht)?

hast du auch ein "hartes problem" irgendwo, dass was nicht mehr geht, oder ist es nur diese "störende notice"?

**Comment by bloep** [comment]
ich nehme an, dass es die Zeile sein wird.
https://github.com/FriendsOfREDAXO/cache_warmup/blob/28e78e0e90fa10074069052e3ff15c43f5c162d7/lib/selector.php#L243

**Comment by staabm** [comment]
Ohh ja, gut möglich. Ich sprech mal für Dirk: PR welcome

**Comment by maxmoeller** [comment]
> gibts im systemlog bissl mehr infos (wo die notice auftaucht)?
> 
> hast du auch ein "hartes problem" irgendwo, dass was nicht mehr geht, oder ist es nur diese "störende notice"?

Danke, erhalte im FE den Fehler


```
verdammt, etwas ist schief gelaufen!
Beim Erzeugen des Caches ist ein Fehler aufgetreten. Details befinden sich auf der Fehlerseite. Wir freuen uns über jede Mithilfe, die Qualität des Addons zu verbessern, indem Fehler bei Github gemeldet werden. Vielen Dank!

(0) → Link zur Fehlerseite
```


im Nginx error | access.log steht nicht viel mehr als das gesendete, vermute mal das der Cache nicht generiert wird, somit nicht unbedingt ein "hartes Problem"


access.log
```
IP - - [27/Sep/2018:14:48:43 +0200] "GET /redaxo/index.php?page=cache_warmup/warmup HTTP/1.1" 200 35734 "https://domain/redaxo/index.php?page=system/cache_warmup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
IP - - [27/Sep/2018:14:48:43 +0200] "GET /assets/addons/rex_redactor2/cache/redactor2_profiles.js?buster=1538052522 HTTP/1.1" 200 2496 "https://domain/redaxo/index.php?page=cache_warmup/warmup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
IP - - [27/Sep/2018:14:48:43 +0200] "GET /redaxo/index.php?page=cache_warmup/generator&pages=1.1,2.1,3.1,4.1,5.1,6.1,7.1,8.1,9.1,10.1,11.1,12.1,13.1,14.1,15.1,16.1,17.1,18.1,20.1,21.1,22.1,23.1,24.1,25.1,27.1,28.1,29.1,31.1,32.1,33.1,34.1,35.1,36.1,37.1,38.1,39.1,40.1,42.1,43.1,44.1,45.1,46.1,47.1,48.1,49.1,50.1,51.1,52.1,53.1,54.1,55.1,56.1,57.1,58.1,59.1,61.1,62.1,63.1,64.1,65.1,67.1,68.1,69.1,70.1,71.1,72.1,73.1,74.1,75.1,76.1,77.1,78.1,79.1,80.1,81.1,82.1,83.1,84.1,85.1,86.1,87.1,88.1,89.1,90.1,91.1,92.1,93.1,94.1,95.1,96.1,98.1,99.1,101.1,103.1,104.1,106.1,107.1,108.1,109.1,110.1,111.1,112.1,113.1,119.1,120.1,121.1,122.1,123.1,127.1,130.1,131.1,132.1,133.1,134.1,135.1,146.1,147.1,148.1,149.1,150.1,151.1,152.1,153.1,154.1,155.1,156.1,157.1,158.1,159.1,160.1,161.1,162.1,168.1,169.1,170.1,171.1,172.1,173.1,175.1,181.1,182.1,183.1,184.1,185.1,186.1,187.1,188.1,189.1,190.1,191.1,193.1,194.1,197.1,198.1,199.1,210.1,213.1,214.1,215.1,216.1,219.1,221.1,223.1,226.1,227.1,228.1,229.1,230.1,231.1,232.1,233.1,234.1,238.1,242.1,243.1,244.1,245.1,246.1,247.1,248.1&_=1538052523661 HTTP/1.1" 301 5 "https://domain/redaxo/index.php?page=cache_warmup/warmup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
IP - - [27/Sep/2018:14:48:43 +0200] "OPTIONS /redaxo/index.php?page=cache_warmup/generator&pages=1.1,2.1,3.1,4.1,5.1,6.1,7.1,8.1,9.1,10.1,11.1,12.1,13.1,14.1,15.1,16.1,17.1,18.1,20.1,21.1,22.1,23.1,24.1,25.1,27.1,28.1,29.1,31.1,32.1,33.1,34.1,35.1,36.1,37.1,38.1,39.1,40.1,42.1,43.1,44.1,45.1,46.1,47.1,48.1,49.1,50.1,51.1,52.1,53.1,54.1,55.1,56.1,57.1,58.1,59.1,61.1,62.1,63.1,64.1,65.1,67.1,68.1,69.1,70.1,71.1,72.1,73.1,74.1,75.1,76.1,77.1,78.1,79.1,80.1,81.1,82.1,83.1,84.1,85.1,86.1,87.1,88.1,89.1,90.1,91.1,92.1,93.1,94.1,95.1,96.1,98.1,99.1,101.1,103.1,104.1,106.1,107.1,108.1,109.1,110.1,111.1,112.1,113.1,119.1,120.1,121.1,122.1,123.1,127.1,130.1,131.1,132.1,133.1,134.1,135.1,146.1,147.1,148.1,149.1,150.1,151.1,152.1,153.1,154.1,155.1,156.1,157.1,158.1,159.1,160.1,161.1,162.1,168.1,169.1,170.1,171.1,172.1,173.1,175.1,181.1,182.1,183.1,184.1,185.1,186.1,187.1,188.1,189.1,190.1,191.1,193.1,194.1,197.1,198.1,199.1,210.1,213.1,214.1,215.1,216.1,219.1,221.1,223.1,226.1,227.1,228.1,229.1,230.1,231.1,232.1,233.1,234.1,238.1,242.1,243.1,244.1,245.1,246.1,247.1,248.1&_=1538052523661 HTTP/1.1" 200 2522 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

```

error.log
```
2018/09/27 15:06:21 [error] 20605#20605: *97791 FastCGI sent in stderr: "PHP message: Undefined variable: item
PHP message: Undefined variable: item
PHP message: Undefined variable: item
PHP message: Undefined variable: item
PHP message: Undefined variable: item
PHP message: Undefined variable: item
PHP message: Undefined variable: item
PHP message: Undefined variable: item
PHP message: Undefined variable: item
PHP message: Undefined variable: item
PHP message: Undefined variable: item
```

Ich weiß die Logs sind nicht  hilfreich, da ich das Projekt von einer Agentur hingeklatscht bekommen habe, fehlt es mir persönlich an den Redaxo Erfahrungen. gibt es ggf. einen Debug Mode für Redaxo | Addons in Redaxo, dann würde selbstverständlich weitere Logs bereit stellen.



```
root@www:/var/www/domain/web/redaxo/cache# ls -al
insgesamt 16
drwxrwxr-x 4 web2 client0 4096 Sep 27 14:58 .
drwxr-xr-x 9 web2 client0 4096 Okt 22  2017 ..
drwxrwxr-x 9 web2 client0 4096 Sep 27 15:01 addons
drwxrwxr-x 2 web2 client0 4096 Sep 27 15:06 core

```

**Comment by schuer** [comment]
Hey @maxmoeller, danke fürs Melden! Mir scheint, irgendwo auf einer Seite (oder auch mehreren) fliegt ein Fehler, weshalb Cache-Warmup abbricht. Man sieht es in deinem access.log bei `/redaxo/index.php?page=cache_warmup/generator&pages=1.1,2.1,3.1,4.1,5 …`. Dieser Fehler wird vermutlich auch auftauchen, wenn du die entsprechende Seite manuell im Browser aufrufst, und nicht nur, wenn der Warmup drüber läuft.

(Die andere Sache, die @bloep entdeckt hat, scheint mir nicht der Grund für deinen Fehler zu sein, wir werden das aber natürlich auch beheben. Gut, dass es aufgefallen ist.)

Falls du Lust hast, der Sache genauer auf die Spur zu gehen, ohne dich durch X Seiten wühlen zu müssen, könntest du in der `boot.php` des AddOns nach der `foreach`-Schleife in Zeile 37 folgendes hinzufügen:

```php
<?php
if (rex_be_controller::getCurrentPage() == 'system/cache_warmup') {
    …
    foreach ($chunksConfig as $k => $v) {
        …
    }

    // Dies hinzufügen:
    $this->setConfig('chunkSizePages', 1);
}
```

Damit wird Cache-Warmup deine Seiten einzeln durchlaufen, und dann kannst du sehen, wo der Fehler fliegt. Diese Seite kannst du dann mal im Browser aufrufen und wirst vermutlich ebenso den Fehler sehen, den du dann im Code deiner Templates oder Module beheben kannst.

Falls du auf all das keine Lust hast: Die nächste große Version des AddOns wird bei Fehlern nicht mehr abbrechen, sondern grundsätzlich bis zum Ende durchlaufen und danach Bescheid geben, ob alles gut gegangen ist. Ich weiß allerdings nicht, wann diese Version fertig wird. Hoffentlich bald…

**Comment by maxmoeller** [comment]
Als Feedback auf die Antwort

Mit der Zeile läuft es wie geschrieben, danke hierfür.

Während des Durchgangs füllt sich das Log mit dem Fehler und bricht abschließend mit "502 Bad Gateway" ab.
```
2018/09/28 11:04:35 [error] 20608#20608: *133665 FastCGI sent in stderr: "PHP message: in_array() expects parameter 2 to be array, string given
PHP message: in_array() expects parameter 2 to be array, string given
PHP message: in_array() expects parameter 2 to be array, string given
PHP message: in_array() expects parameter 2 to be array, string given" while reading response header from upstream, client: IP, server: domain.de, request: "GET /redaxo/index.php?page=cache_warmup/generator&images=3844.Sliderbilder,3844.spaltenbild,3844.spalteSingle,3844.Testimonial,3844.topdf,3843.Ansprechpartner,3843.GalleryImg,3843.NewsImg,3843.rex_mediabutton_preview,3843.rex_medialistbutton_preview,3843.rex_mediapool_detail,3843.rex_mediapool_maximized&_=1538124643294 HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php7.0-fpm/web2.sock:", host: "www.domain.de", referrer: "https://www.domain.de/redaxo/index.php?page=cache_warmup/warmup"


2018/09/28 11:29:51 [error] 20602#20602: *134553 FastCGI sent in stderr: "PHP message: in_array() expects parameter 2 to be array, string given
PHP message: in_array() expects parameter 2 to be array, string given" while reading response header from upstream, client: IP, server: DOMAIN, request: "GET /redaxo/index.php?page=cache_warmup/generator&images=4338.rex_mediapool_detail,4338.rex_mediapool_maximized,4338.rex_mediapool_preview,4338.Sliderbilder,4338.spaltenbild,4338.spalteSingle,4338.Testimonial,4338.topdf,4337.Ansprechpartner,4337.GalleryImg,4337.NewsImg,4337.rex_mediabutton_preview&_=1538124643497 HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php7.0-fpm/web2.sock:", host: "DOMAIN", referrer: "https://DOMAIN/redaxo/index.php?page=cache_warmup/warmup"
2018/09/28 11:30:02 [error] 20602#20602: *134553 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: IP, server: DOMAIN, request: "GET /redaxo/index.php?page=cache_warmup/generator&images=4337.rex_medialistbutton_preview,4337.rex_mediapool_detail,4337.rex_mediapool_maximized,4337.rex_mediapool_preview,4337.Sliderbilder,4337.spaltenbild,4337.spalteSingle,4337.Testimonial,4337.topdf,4336.Ansprechpartner,4336.GalleryImg,4336.NewsImg&_=1538124643498 HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php7.0-fpm/web2.sock:", host: "DOMAIN", referrer: "https://DOMAIN/redaxo/index.php?page=cache_warmup/warmup"

```
Denke der Fehler liegt hier an anderer Stelle.

Danke für die prompte Untersützung!

**Comment by schuer** [comment]
Danke fürs Debuggen, @maxmoeller! Jetzt sind wir einen Schritt weiter. Offenbar läuft die Generierung aller Seiten nun problemlos durch, wenn du sie einzeln anforderst. Das deutet auf einen vorherigen Timeout hin, dass also zuvor das Generieren der Seiten zu lange gedauert hat und damit die max execution time erreicht worden ist. Einzeln durchlaufen fliegt kein Timeout mehr, und die bist nun beim Generieren der Bilder angelangt.

Hier hast du nun ein ähnliches Problem, nämlich Timeout oder zu wenig RAM, und du könntest bei Interesse prüfen, indem du eine weitere Zeile in der `boot.php` vor oder hinter der anderen Zeile hinzufügst:

```php
$this->setConfig('chunkSizeImages', 1);
```

Damit werden auch die Bilder einzeln generiert, und dann wird sich ebenso zeigen, bei welchem Bild der Prozess abbricht:

Möglichkeit A): Wenn der Prozess nicht abbricht, bedeutet es, dass dein RAM ausreicht, und dass lediglich zu viele Objekte gleichzeitig generiert werden. Hier könntest du Abhilfe schaffen, indem du die beiden Zeilen vorerst in der `boot.php` belässt und ggfls die Werte noch etwas erhöhst, damit die Cache-Generierung nicht so lange dauert.

Möglichkeit B): Wenn der Prozess abbricht, bedeutet es, dass das Bild zu groß ist, um von REDAXO bearbeitet zu werden, und dann wird dieses Bild auch auf deiner Website nicht zu sehen sein. Dem Server fehlen dann schlicht die Ressourcen, und du kannst dann nur Abhilfe schaffen, indem du die Ressourcen erhöhst (Hosting mit mehr RAM) oder das Originalbild im Medienpool verkleinerst.

---

Und auch hier wieder der Hinweis auf die weitere Entwicklung: Das AddOn wird in zukünftigen Versionen auch einen Timeout zu verhindern wissen, indem es versucht, die Anzahl der zu Generierenden Objekte zu verringern, wenn die Ressourcen nicht ausreichen. Werden also beispielsweise 10 Bilder in einem Rutsch generiert, und der Server wirft einen Fehler, dann wird das AddOn zukünftig einen erneuten Anlauf starten, und diesmal aber nur mit 5 Bildern gleichzeitig. Wenn das auch nicht ausreicht, wird weiter reduziert, bis am Ende nur noch 1 Bild übrig bleibt. Und wenn das auch nicht mehr klappt, ist klar, dass der Server zu wenig RAM hat, dann wird vom AddOn anschließend ein Hinweis darauf ausgegeben werden.

**Comment by iamjonasmarlo** [comment]
Hallo zusammen,
ich habe das selbe Problem.

Redaxo 5.6.3
PHP 7.2.4

Ich habe sowohl `$this->setConfig('chunkSizePages', 1);` als auch `$this->setConfig('chunkSizeImages', 1);` in die `boot.php` integriert, leider ohne Erfolg.
Das generieren des Caches beginnt und bricht nach ungefähr einer halben Sekunde mit der selben Fehlermeldung ab.

Die Fehlerseite, welche mir angeboten wird, ist komplett leer.

**Comment by schuer** [comment]
@iamjonasmarlo Danke auch für deine Meldung! Freue mich immer, wenn hier Feedback kommt.

An der URL zur Fehlerseite siehst du, welche Objekte nicht generiert werden konnten. Die URL beginnt mit `/redaxo/index.php?page=cache_warmup/generator&pages=…` (pages) oder `/redaxo/index.php?page=cache_warmup/generator&images=` (images), wobei die Pages zuerst generiert werden. Ich vermute, du hast irgendwo einen Fehler auf einer der Seiten, so dass Cache-Warmup abbricht. Diesen Fehler solltest du dann auch sehen, wenn du die entsprechende Seite im Frontend aufrufst. Um rauszufinden, welche Seite es ist, schau dir den Parameter hinter `&pages=…` an. Er lautet beispielsweise `32.1`, wobei 32 die pageID ist und 1 die clang, also die Sprache.

Ich bin sehr gespannt, ob es so ist, und ob du diesen Fehler auch im Frontend siehst. Magst du das mal testen?

**Comment by iamjonasmarlo** [comment]
@schuer Vielen Dank für dein schnelles Feedback! :) Ist leider echt selten, dass einem so schnell und vor allem so gerne geholfen wird. Danke dafür!

Folgende URL wird mir ausgeworfen: 
`/redaxo/index.php?page=cache_warmup/generator&pages=1.1`

Die Seite mit der ID 1 ist meine Startseite und funktioniert ohne Probleme im Frontend. Seltsam...

Edit:

Ich verwende Redaxo mit YRewrite. In meinem Fall ist jede angelegte Kategorie ein Standort, welche sich über eine Subdomain aufrufen lässt. Dafür sorgt eben YRewrite. Wenn der Nutzer Beispielsweise https://berlin.meineseite.de aufruft, landet er in der Kategorie "Berlin". Vielleicht liegt hier irgendwo der Fehler?

**Comment by schuer** [comment]
@iamjonasmarlo Danke für den Hinweis mit YRewrite! Sehr gut möglich, dass es an dem Setup liegt. Cache-Warmup selektiert alle im CMS angelegten Einzelseiten, unabhängig von irgendwelchen Zugriffsrechten. Wenn nun YRewrite abhängig von der aufgerufenen Subdomain den Zugriff eingrenzt, kann gut sein, dass Cache-Warmup Fehler produziert, wenn es versucht, auf Bereiche außerhalb der Subdomain zuzugreifen. Dafür müsste ich mir YRewrite mal genauer anschauen bei Gelegenheit.

Ich fürchte, solange es keinen Fix dafür gibt, wirst du Cache-Warmup nicht verwenden können. Tut mir leid.

**Comment by iamjonasmarlo** [comment]
@schuer Trotzdem vielen Dank für deine Hilfe! Vielleicht gibt es ja in naher Zukunft einen Fix. Bis dahin!

**Comment by schuer** [comment]
Eine neue Version 3.4.0 wurde übrigens gerade veröffentlicht, die den oben genannten Bugfix (entdeckt von @bloep, gefixt von @staabm) enthält. Die beiden Issues hier in der Diskussion wird sie aber sicherlich nicht beheben.

**Comment by maxmoeller** [comment]
Kurzes Update:

Habe heute das Update auf Redaxo 5.6.4 gemacht und Cache-Warmup auf 3.4. Keine Änderungen an der Serverkonfiguration durchgeführt und der Cache wurde generiert.

```
Der Cache wurde für 204 Seiten und 9789 Bilder vorbereitet. Das hat etwa 00:54:32 gedauert und sorgt dafür, dass nun niemand mehr bei den ersten Seitenaufrufen unnötig lange warten muss.
```

Da RAM etc ein Thema war, PHP.ini

```
max_execution_time  30 sek;
memory_limit		512MB;
```

Serverlast war insgesamt minimal, kein SWAP etc.

Bezüglich dem YRewrite - nutzen wir in einem Multi-Domain-Setup - ist mir aufgefallen, das Cache-Warmup nur auf der initial Domain (ID 1) fehlerfrei läuft, auf den anderen Domain bricht es direkt zu beginn mit o.g. Fehler "...etwas ist schief gelaufen.. " ab.

**Comment by schuer** [comment]
Super dass es durchgelaufen ist, @maxmoeller. Vielleicht lag es doch an dem Bugfix von @bloep und @staabm, denn es vorher wurden die Medieninstanzen nach Benutzung nicht ordentlich aufgeräumt, und vielleicht ist dadurch der RAM zu voll gelaufen.

Das Problem mit YRewrite und Multi-Domain schaue ich mir an. Es scheint ja der gleiche oder ein ähnlicher Fehler wie bei @iamjonasmarlo zu sein. Danke für eure Hinweise!

**Comment by AWqxKAWERbXo** [comment]
Läuft bestens durch auf 2 verschiedenen Multidomain-Projekten
